set(ROUSE_EMSCRIPTEN ON CACHE BOOL OFF FORCE)
set(CMAKE_C_COMPILER_ID Clang CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_VERSION 6.0.1 CACHE STRING "" FORCE)
set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 11 CACHE STRING "" FORCE)
