#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename qw(dirname);
use File::Spec::Functions qw(catfile);

die "Usage: $0 SOURCE_FILE\n" if @ARGV != 1;

my $path = catfile(dirname(shift), 'preload-files');

open my $fh, '<', $path or die "Can't open '$path': $!\n";

while (<$fh>) {
    next unless /\S/;
    s/\A\s+|\s+\z//g;
    print " --preload-file $_";
}

print "\n";
close $fh or warn "Can't close '$path': $!\n";
