#!/bin/bash
#
# get-imgui - grabs the Dear Imgui sources
#
# Copyright (c) 2021 askmeaboutloom
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
IMGUI_GIT_URL='https://github.com/ocornut/imgui.git'
IMGUI_GIT_CHECKOUT='f99fe72c42bd5d578c2443409192b139b1c6623d'

IMNODES_GIT_URL='https://github.com/Nelarius/imnodes.git'
IMNODES_GIT_CHECKOUT='c63f347f06f16f78249bdd0914b1bc04dabc4f0a'

set -e
cd "$(dirname "$0")"

mkdir -p lib/3rdparty
cd lib/3rdparty


if ! [ -e imgui_git ]; then
    git clone "$IMGUI_GIT_URL" imgui_git
fi

cd imgui_git
git checkout "$IMGUI_GIT_CHECKOUT"
git config --local user.name rouse
git config --local user.email rouse@example.com
git am ../imgui/rouse.patch

cp -v LICENSE.txt \
      backends/imgui_impl_opengl3.cpp \
      backends/imgui_impl_opengl3.h \
      backends/imgui_impl_sdl.cpp \
      backends/imgui_impl_sdl.h \
      imconfig.h \
      imgui.cpp \
      imgui.h \
      imgui_demo.cpp \
      imgui_draw.cpp \
      imgui_internal.h \
      imgui_tables.cpp \
      imgui_widgets.cpp \
      imstb_rectpack.h \
      imstb_textedit.h \
      imstb_truetype.h \
      ../imgui

cd ..


if ! [ -e imnodes_git ]; then
    git clone "$IMNODES_GIT_URL" imnodes_git
fi

cd imnodes_git
git checkout "$IMNODES_GIT_CHECKOUT"

cp -v LICENSE.md \
      imnodes.cpp \
      imnodes.h \
      imnodes_internal.h \
      ../imnodes

cd ..
