# Automatically generated by generate-source-lists

set(rouse_headers
    "${CMAKE_BINARY_DIR}/config/rouse_config.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/bitmap.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/nvg.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/sprite.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/sprite_anim.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/text.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/vector.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/GLES2/gl2.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/GLES2/gl2ext.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/GLES2/gl2platform.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/KHR/khrplatform.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/gles2_inc.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg_inc.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/openal_inc.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/call.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/delay.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/ease.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/seq.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/tween.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/util.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/camera.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/common.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/dl.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/geom.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/json.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/main.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/model.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/parse.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/refcount.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/binder.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/frame_buffer.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/frame_renderer.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/gl.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/viewport.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/sanity.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/string.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/stringify.h")

set(rouse_sources
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/bitmap.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/nvg.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/sprite.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/sprite_anim.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/text.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/2d/vector.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/call.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/delay.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/ease.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/seq.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/tween.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/anim/util.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/camera.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/common.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/json.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/main.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/model.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/parse.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/binder.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/frame_buffer.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/frame_renderer.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/gl.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/render/viewport.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/string.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/stringify.c")

set(parson_headers
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/parson.h")

set(parson_sources
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/parson.c")

set(nanovg_headers
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/fontstash.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/nanovg.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/nanovg_gl.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/nanovg_gl_utils.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/stb_image.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/stb_truetype.h")

set(nanovg_sources
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg/nanovg.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/nanovg_gles2.c")

set(stb_vorbis_headers
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/stb_vorbis.h")

set(stb_vorbis_sources
    "${CMAKE_SOURCE_DIR}/lib/rouse/3rdparty/stb_vorbis.c")

set(rouse_audio_headers
    "${CMAKE_SOURCE_DIR}/lib/rouse/audio/al.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/audio/sample.h"
    "${CMAKE_SOURCE_DIR}/lib/rouse/audio/sound_anim.h")

set(rouse_audio_sources
    "${CMAKE_SOURCE_DIR}/lib/rouse/audio/al.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/audio/sample.c"
    "${CMAKE_SOURCE_DIR}/lib/rouse/audio/sound_anim.c")
