option(BUILD_WITH_BOX2D          "enable Box2D bindings"               ON)
option(BUILD_WITH_IMGUI          "enable Dear Imgui bindings"          ON)
option(BUILD_WITH_POCKETSPHINX   "enable PhocketSphinx bindings"       OFF)
option(BUILD_WITH_STATIC_CXXLIBS "build with static GCC C++ libraries" OFF)
option(USE_PKGCONFIG             "use pkg-config to find libraries"    ON)
