/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2020 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"
#include "main.h"

static double to_double(lua_State *L, int arg)
{
    void *u = luaL_testudata(L, arg, "double");
    if (u) {
        return *((double *)u);
    }
    else if (lua_isstring(L, arg)) {
        size_t len;
        const char *s = lua_tolstring(L, arg, &len);
        char *end;
        double d = strtod(s, &end);
        if (end == s + len && end != s) {
            return d;
        }
    }
    else {
        int ok;
        lua_Number n = lua_tonumberx(L, arg, &ok);
        if (ok) {
            return (double) n;
        }
    }
    luaL_argerror(L, arg, "not a double");
    R_UNREACHABLE();
}


static int r_double_new_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = to_double(L, 1);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_tostring_xl(lua_State *L)
{
    double self = to_double(L, 1);
    char *fmt = R_format("%f", self);
    lua_pushstring(L, fmt);
    free(fmt);
    return 1;
}

static int double_method_add_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = to_double(L, 1) + to_double(L, 2);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_sub_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = to_double(L, 1) - to_double(L, 2);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_mul_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = to_double(L, 1) * to_double(L, 2);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_div_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = to_double(L, 1) / to_double(L, 2);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_pow_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = pow(to_double(L, 1), to_double(L, 2));
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_unm_xl(lua_State *L)
{
    double RETVAL;
    RETVAL = -to_double(L, 1);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(double), "double", 0);
    return 1;
}

static int double_method_eq_xl(lua_State *L)
{
    bool RETVAL;
    RETVAL = to_double(L, 1) == to_double(L, 2);
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int double_method_lt_xl(lua_State *L)
{
    bool RETVAL;
    RETVAL = to_double(L, 1) < to_double(L, 2);
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int double_method_le_xl(lua_State *L)
{
    bool RETVAL;
    RETVAL = to_double(L, 1) <= to_double(L, 2);
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int double_method_to_integer_xl(lua_State *L)
{
    double *self = R_CPPCAST(double *, XL_checkutype(L, 1, "double"));
    lua_Integer RETVAL;
    RETVAL = (lua_Integer) *self;
    lua_pushinteger(L, RETVAL);
    return 1;
}

static int double_method_sep_rounded_xl(lua_State *L)
{
    double *self = R_CPPCAST(double *, XL_checkutype(L, 1, "double"));
    char *s = R_format("%.0f", round(*self));
    size_t len = strlen(s);

    luaL_Buffer b;
    luaL_buffinitsize(L, &b, len + len / 3 + 1);

    for (size_t i = 0; i < len; ++i) {
        char c = s[len - i - 1];
        luaL_addchar(&b, c);
        if ((i + 1) % 3 == 0 && i != 0 && i != len - 1) {
            luaL_addchar(&b, ',');
        }
    }

    free(s);

    lua_getglobal(L, "string");
    lua_getfield(L, -1, "reverse");
    luaL_pushresult(&b);
    lua_call(L, 1, 1);
    return 1;
}

#ifdef __cplusplus
extern "C" {
#endif

static int double_index_xl(lua_State *L)
{
    return XL_index_fallback(L, "double", 1, 2);
}

static luaL_Reg r_double_function_registry_xl[] = {
    {"new", r_double_new_xl},
    {NULL, NULL},
};

static luaL_Reg double_method_registry_xl[] = {
    {"__add", double_method_add_xl},
    {"__div", double_method_div_xl},
    {"__eq", double_method_eq_xl},
    {"__index", double_index_xl},
    {"__le", double_method_le_xl},
    {"__lt", double_method_lt_xl},
    {"__mul", double_method_mul_xl},
    {"__pow", double_method_pow_xl},
    {"__sub", double_method_sub_xl},
    {"__tostring", double_method_tostring_xl},
    {"__unm", double_method_unm_xl},
    {"sep_rounded", double_method_sep_rounded_xl},
    {"to_integer", double_method_to_integer_xl},
    {NULL, NULL},
};

int R_lua_double_init(lua_State *L)
{
    XL_initmetatable(L, "double", double_method_registry_xl);
    XL_initfunctions(L, r_double_function_registry_xl, "R", "Double", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
