/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_framerenderer_new_xl(lua_State *L)
{
    R_FrameRenderer *RETVAL;
    bool alpha_blending = lua_toboolean(L, 1);
    RETVAL = R_frame_renderer_new(alpha_blending);
    XL_pushnewpptypeuv(L, RETVAL, "R_FrameRenderer", 0);
    return 1;
}

static int r_framerenderer_method_gc_xl(lua_State *L)
{
    R_FrameRenderer *self = R_CPPCAST(R_FrameRenderer *, XL_checkpptype_nullable(L, 1, "R_FrameRenderer"));
    R_frame_renderer_free(self);
    return 0;
}

static int r_framerenderer_method_draw_xl(lua_State *L)
{
    R_FrameRenderer *self = R_CPPCAST(R_FrameRenderer *, XL_checkpptype(L, 1, "R_FrameRenderer"));
    R_FrameBuffer *fb = R_CPPCAST(R_FrameBuffer *, XL_checkpptype(L, 2, "R_FrameBuffer"));
    R_frame_renderer_draw(self, fb);
    return 0;
}

#ifdef __cplusplus
extern "C" {
#endif

static int r_framerenderer_index_xl(lua_State *L)
{
    return XL_index_fallback(L, "R_FrameRenderer", 1, 2);
}

static luaL_Reg r_framerenderer_function_registry_xl[] = {
    {"new", r_framerenderer_new_xl},
    {NULL, NULL},
};

static luaL_Reg r_framerenderer_method_registry_xl[] = {
    {"__gc", r_framerenderer_method_gc_xl},
    {"__index", r_framerenderer_index_xl},
    {"draw", r_framerenderer_method_draw_xl},
    {NULL, NULL},
};

int R_lua_frame_renderer_init(lua_State *L)
{
    XL_initmetatable(L, "R_FrameRenderer", r_framerenderer_method_registry_xl);
    XL_initfunctions(L, r_framerenderer_function_registry_xl, "R", "FrameRenderer", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
