/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_gl_clear_xl(lua_State *L)
{
    float r = XL_checkfloat(L, 1);
    float g = XL_checkfloat(L, 2);
    float b = XL_checkfloat(L, 3);
    float a = XL_checkfloat(L, 4);
    float depth = XL_checkfloat(L, 5);
    int stencil = XL_checkint(L, 6);
    R_gl_clear(r, g, b, a, depth, stencil);
    return 0;
}

#ifdef __cplusplus
extern "C" {
#endif

static luaL_Reg r_gl_function_registry_xl[] = {
    {"clear", r_gl_clear_xl},
    {NULL, NULL},
};

int R_lua_gl_init(lua_State *L)
{
    XL_initfunctions(L, r_gl_function_registry_xl, "R", "GL", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
