/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"

static void value_to_lua(lua_State *L, JSON_Value *value);

static void object_to_lua(lua_State *L, JSON_Object *object)
{
    size_t count = json_object_get_count(object);
    lua_createtable(L, 0, R_size2int(count));

    for (size_t i = 0; i < count; ++i) {
        value_to_lua(L, json_object_get_value_at(object, i));
        lua_setfield(L, -2, json_object_get_name(object, i));
    }
}

static void array_to_lua(lua_State *L, JSON_Array *array)
{
    size_t count = json_array_get_count(array);
    lua_createtable(L, R_size2int(count), 0);

    for (size_t i = 0; i < count; ++i) {
        value_to_lua(L, json_array_get_value(array, i));
        lua_seti(L, -2, R_lua_size2i(i) + 1);
    }
}

static void value_to_lua(lua_State *L, JSON_Value *value)
{
    JSON_Value_Type type = json_type(value);
    switch (type) {
        case JSONNull:
            lua_pushnil(L);
            break;
        case JSONString:
            lua_pushstring(L, json_string(value));
            break;
        case JSONNumber:
            lua_pushnumber(L, R_lua_double2n(json_number(value)));
            break;
        case JSONObject:
            object_to_lua(L, json_object(value));
            break;
        case JSONArray:
            array_to_lua(L, json_array(value));
            break;
        case JSONBoolean:
            lua_pushboolean(L, json_boolean(value));
            break;
        default:
            luaL_error(L, "Unknown JSON value type %d", (int) type);
    }
}

static int protected_table_from_json(lua_State *L)
{
    JSON_Value *value = lua_touserdata(L, 1);
    value_to_lua(L, value);
    return 1;
}

static int push_table_from_json(lua_State *L, JSON_Value *value)
{
    lua_pushcfunction(L, protected_table_from_json);
    lua_pushlightuserdata(L, value);
    int error = lua_pcall(L, 1, 1, 0);
    json_value_free(value);
    return error ? lua_error(L) : 1;
}


static int r_json_parse_string_xl(lua_State *L)
{
    const char *string = luaL_checkstring(L, 1);
    bool with_comments = lua_toboolean(L, 2);

    JSON_Value *value = with_comments
                      ? json_parse_string_with_comments(string)
                      : json_parse_string(string);
    if (!value) {
        luaL_error(L, "Can't parse JSON string (%s comments) '%s'", string,
                   with_comments ? "with" : "without");
    }
    return push_table_from_json(L, value);
}

static int r_json_parse_file_xl(lua_State *L)
{
    const char *filename = luaL_checkstring(L, 1);
    bool with_comments = lua_toboolean(L, 2);

    JSON_Value *value = with_comments
                      ? json_parse_file_with_comments(filename)
                      : json_parse_file(filename);
    if (!value) {
        luaL_error(L, "Can't parse JSON file (%s comments) '%s'",
                   filename, with_comments ? "with" : "without");
    }
    return push_table_from_json(L, value);
}

static luaL_Reg r_json_function_registry_xl[] = {
    {"parse_file", r_json_parse_file_xl},
    {"parse_string", r_json_parse_string_xl},
    {NULL, NULL},
};

int R_lua_json_init(lua_State *L)
{
    XL_initfunctions(L, r_json_function_registry_xl, "R", "Json", (const char *)NULL);
    return 0;
}
