/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"
#include "main.h"

static void log_message(lua_State *L, void (*log_fn)(const char *, int,
                                                     const char *, ...))
{
    int argc = lua_gettop(L);
    lua_getglobal(L, "string");
    lua_getfield(L, -1, "format");
    lua_insert(L, 1);
    lua_pop(L, 1);
    lua_call(L, argc, 1);
    const char *message = lua_tostring(L, -1);

    lua_Debug ar;
    lua_getstack(L, 1, &ar);
    lua_getinfo(L, "Sl", &ar);
    const char *file = ar.currentline > 0 ? ar.short_src : "(unknown)";

    log_fn(file, ar.currentline, "%s", message);
}


static int r_log_enable_xl(lua_State *L)
{
    unsigned int logbits = XL_checkuint(L, 1);
    R_log_enable(logbits);
    return 0;
}

static int r_log_disable_xl(lua_State *L)
{
    unsigned int logbits = XL_checkuint(L, 1);
    R_log_disable(logbits);
    return 0;
}

static int r_debug_xl(lua_State *L)
{
    log_message(L, R_debug_fn);
    return 0;
}

static int r_info_xl(lua_State *L)
{
    log_message(L, R_info_fn);
    return 0;
}

static int r_warn_xl(lua_State *L)
{
    log_message(L, R_warn_fn);
    return 0;
}

static int r_die_xl(lua_State *L)
{
    log_message(L, R_die_fn);
    return 0;
}

static int r_get_platform_xl(lua_State *L)
{
    const char *RETVAL;
    RETVAL = ROUSE_PLATFORM;
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_set_framerate_xl(lua_State *L)
{
    float ticks_per_second = XL_checkfloat(L, 1);
    R_framerate_set(ticks_per_second);
    return 0;
}

static int r_set_max_ticks_before_render_xl(lua_State *L)
{
    uint32_t max_ticks_before_render = XL_checkuint32(L, 1);
    R_max_ticks_before_render = max_ticks_before_render;
    return 0;
}

static int r_rand_between_xl(lua_State *L)
{
    float a = XL_checkfloat(L, 1);
    float b = XL_checkfloat(L, 2);
    float RETVAL;
    RETVAL = R_rand_between(a, b);
    XL_pushfloat(L, RETVAL);
    return 1;
}


static int on_fetch_done(lua_State *L)
{
    lua_pushvalue(L, lua_upvalueindex(1));
    lua_call(L, 0, 0);
    return 0;
}


static int r_fetch_xl(lua_State *L)
{
    const char *url = luaL_checkstring(L, 1);
    const char *path = luaL_checkstring(L, 2);
    luaL_checkany(L, 3);
    int on_done = 3;
    lua_pushvalue(L, on_done);
    lua_pushcclosure(L, on_fetch_done, 1);
    R_lua_fetch(L, url, path);
    return 0;
}

static luaL_Reg r_function_registry_xl[] = {
    {"debug", r_debug_xl},
    {"die", r_die_xl},
    {"fetch", r_fetch_xl},
    {"get_platform", r_get_platform_xl},
    {"info", r_info_xl},
    {"rand_between", r_rand_between_xl},
    {"set_framerate", r_set_framerate_xl},
    {"set_max_ticks_before_render", r_set_max_ticks_before_render_xl},
    {"warn", r_warn_xl},
    {NULL, NULL},
};

static luaL_Reg r_log_function_registry_xl[] = {
    {"disable", r_log_disable_xl},
    {"enable", r_log_enable_xl},
    {NULL, NULL},
};

static XL_EnumEntry r_logbit_enum_xl[] = {
    {"DEBUG", (lua_Integer) R_LOGBIT_DEBUG},
    {"INFO", (lua_Integer) R_LOGBIT_INFO},
    {"WARN", (lua_Integer) R_LOGBIT_WARN},
    {"DIE", (lua_Integer) R_LOGBIT_DIE},
    {NULL, (lua_Integer) 0},
};

int R_lua_misc_init(lua_State *L)
{
    XL_initfunctions(L, r_function_registry_xl, "R", (const char *)NULL);
    XL_initfunctions(L, r_log_function_registry_xl, "R", "log", (const char *)NULL);
    XL_initenum(L, r_logbit_enum_xl, "R", "Logbit", (const char *)NULL);
    return 0;
}
