/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2021 - 2022 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_meshbuffer_new_xl(lua_State *L)
{
    const char *type_name = luaL_checkstring(L, 1);
    const char *name = luaL_checkstring(L, 2);
    int count = XL_checkint(L, 3);
    int divisor = XL_checkint(L, 4);
    R_MeshBuffer *RETVAL;
    R_BufferType type;
    if (R_str_equal(type_name, "float")) {
        type = R_BUFFER_TYPE_FLOAT;
    }
    else if (R_str_equal(type_name, "ushort")) {
        type = R_BUFFER_TYPE_USHORT;
    }
    else {
        R_LUA_DIE(L, "Unknown mesh buffer type '%s'", type_name);
    }

    if (count <= 0) {
        R_LUA_DIE(L, "Invalid mesh buffer count %d", count);
    }
    if (divisor <= 0) {
        R_LUA_DIE(L, "Invalid mesh buffer divisor %d", divisor);
    }
    if (count % divisor != 0) {
        R_LUA_DIE(L, "Mesh buffer count %d is not divisible by %d",
                  count, divisor);
    }

    RETVAL = R_mesh_buffer_new(type, name, count, divisor);
    XL_pushnewpptypeuv(L, RETVAL, "R_MeshBuffer", 0);
    return 1;
}

static int r_meshbuffer_method_gc_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype_nullable(L, 1, "R_MeshBuffer"));
    R_mesh_buffer_decref(self);
    return 0;
}

static int r_meshbuffer_refs_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_meshbuffer_name_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    const char *RETVAL;
    RETVAL = self->name;
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_meshbuffer_count_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    int RETVAL;
    RETVAL = self->count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_meshbuffer_divisor_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    int RETVAL;
    RETVAL = self->divisor;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_meshbuffer_type_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    lua_Integer RETVAL;
    RETVAL = (lua_Integer) self->type;
    lua_pushinteger(L, RETVAL);
    return 1;
}

static int r_meshbuffer_type_name_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    const char *RETVAL;
    switch (self->type) {
        case R_BUFFER_TYPE_USHORT:
            RETVAL = "ushort";
            break;
        case R_BUFFER_TYPE_FLOAT:
            RETVAL = "float";
            break;
        default:
            RETVAL = "unknown";
            break;
    }
    lua_pushstring(L, RETVAL);
    return 1;
}


#define INDEX_VALUES(L, MBUF, PUSH, TYPE, FIELD) do { \
        int _count = (MBUF)->count; \
        lua_createtable(L, _count, 0); \
        TYPE *FIELD = (MBUF)->values.FIELD; \
        for (int _i = 0; _i < _count; ++_i) { \
            PUSH(L, FIELD[_i]); \
            lua_seti(L, -2, _i + 1); \
        } \
    } while (0)

#define NEWINDEX_VALUES(L, MBUF, TABLE, COUNT, CHECK, TYPE, FIELD) do { \
        TYPE *FIELD = (MBUF)->values.FIELD; \
        for (int _i = 0; _i < (COUNT); ++_i) { \
            lua_geti(L, TABLE, _i + 1); \
            FIELD[_i] = CHECK(L, -1); \
            lua_pop(L, 1); \
        } \
    } while (0)


static int r_meshbuffer_values_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    switch (self->type) {
        case R_BUFFER_TYPE_USHORT:
            INDEX_VALUES(L, self, XL_pushushort, unsigned short, ushorts);
            break;
        case R_BUFFER_TYPE_FLOAT:
            INDEX_VALUES(L, self, XL_pushfloat, float, floats);
            break;
        default:
            R_LUA_DIE(L, "Unknown mesh buffer type '%d'", (int) self->type);
    }
    return 1;
}

static int r_meshbuffer_values_newindex_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    luaL_checktype(L, 2, LUA_TTABLE);
    int VALUE = 2;
    int len = (int) luaL_len(L, VALUE);
    if (len != self->count) {
        R_LUA_DIE(L, "Got %d values, but need %d", len, self->count);
    }
    switch (self->type) {
        case R_BUFFER_TYPE_USHORT:
            NEWINDEX_VALUES(L, self, VALUE, len, XL_checkushort,
                            unsigned short, ushorts);
            break;
        case R_BUFFER_TYPE_FLOAT:
            NEWINDEX_VALUES(L, self, VALUE, len, XL_checkfloat,
                            float, floats);
            break;
        default:
            R_LUA_DIE(L, "Unknown mesh buffer type '%d'", (int) self->type);
    }
    return 0;
}


static void check_mesh_buffer_index(lua_State *L, R_MeshBuffer *mbuf, int index)
{
    if (index < 1 || index > mbuf->count) {
        R_LUA_DIE(L, "Mesh buffer index %d out of range", index);
    }
}


static int r_meshbuffer_intindex_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    lua_Integer INDEX = luaL_checkinteger(L, 2);
    check_mesh_buffer_index(L, self, INDEX);
    switch (self->type) {
        case R_BUFFER_TYPE_USHORT:
            XL_pushushort(L, self->values.ushorts[INDEX - 1]);
            break;
        case R_BUFFER_TYPE_FLOAT:
            XL_pushfloat(L, self->values.floats[INDEX - 1]);
            break;
        default:
            R_LUA_DIE(L, "Unknown mesh buffer type '%d'", (int) self->type);
    }
    return 1;
}

static int r_meshbuffer_intnewindex_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    lua_Integer INDEX = luaL_checkinteger(L, 2);
    luaL_checkany(L, 3);
    int VALUE = 3;
    check_mesh_buffer_index(L, self, INDEX);
    switch (self->type) {
        case R_BUFFER_TYPE_USHORT:
            self->values.ushorts[INDEX - 1] = XL_checkushort(L, VALUE);
            break;
        case R_BUFFER_TYPE_FLOAT:
            self->values.floats[INDEX - 1] = XL_checkfloat(L, VALUE);
            break;
        default:
            R_LUA_DIE(L, "Unknown mesh buffer type '%d'", (int) self->type);
    }
    return 0;
}

static int r_mesh_method_gc_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype_nullable(L, 1, "R_Mesh"));
    R_mesh_decref(self);
    return 0;
}

static int r_mesh_refs_index_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype(L, 1, "R_Mesh"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_mesh_buffer_count_index_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype(L, 1, "R_Mesh"));
    int RETVAL;
    RETVAL = self->buffer.count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_mesh_method_buffer_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype(L, 1, "R_Mesh"));
    R_MeshBuffer *RETVAL;
    int type = lua_type(L, 2);
    if (type == LUA_TNUMBER) {
        int index = XL_checkint(L, 2);
        if (index > 0 && index <= self->buffer.count) {
            RETVAL = R_mesh_buffer_incref(self->buffer.values[index - 1]);
        }
        else {
            R_LUA_DIE(L, "Mesh buffer index %d out of bounds [1, %d]",
                      index, self->buffer.count);
        }
    }
    else if (type == LUA_TSTRING) {
        const char *name = lua_tostring(L, 2);
        int index = R_mesh_buffer_index_by_name(self, name);
        if (index >= 0) {
            RETVAL = R_mesh_buffer_incref(self->buffer.values[index]);
        }
        else {
            R_LUA_DIE(L, "Mesh buffer with name '%s' not found", name);
        }
    }
    else {
        R_LUA_DIE(L, "Can't get a mesh buffer by a %s", lua_typename(L, type));
    }
    XL_pushnewpptypeuv(L, RETVAL, "R_MeshBuffer", 0);
    return 1;
}

static int r_node_method_gc_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype_nullable(L, 1, "R_Node"));
    R_node_decref(self);
    return 0;
}

static int r_node_refs_index_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_node_name_index_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    const char *RETVAL;
    RETVAL = self->name;
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_node_transform_index_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    R_M4 RETVAL;
    RETVAL = self->transform;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_M4), "R_M4", 0);
    return 1;
}

static int r_node_child_count_index_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    int RETVAL;
    RETVAL = self->child.count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_node_mesh_count_index_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    int RETVAL;
    RETVAL = self->mesh.count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_node_method_child_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    int index = XL_checkint(L, 2);
    R_Node *RETVAL;
    if (index > 0 && index <= self->child.count) {
        RETVAL = R_node_incref(self->child.values[index - 1]);
    }
    else {
        R_LUA_DIE(L, "Node child index %d out of bounds [1, %d]",
                  index, self->mesh.count);
    }
    XL_pushnewpptypeuv(L, RETVAL, "R_Node", 0);
    return 1;
}

static int r_node_method_mesh_xl(lua_State *L)
{
    R_Node *self = R_CPPCAST(R_Node *, XL_checkpptype(L, 1, "R_Node"));
    int index = XL_checkint(L, 2);
    R_Mesh *RETVAL;
    if (index > 0 && index <= self->mesh.count) {
        RETVAL = R_mesh_incref(self->mesh.values[index - 1]);
    }
    else {
        R_LUA_DIE(L, "Node mesh index %d out of bounds [1, %d]",
                  index, self->mesh.count);
    }
    XL_pushnewpptypeuv(L, RETVAL, "R_Mesh", 0);
    return 1;
}

static int r_model_from_file_xl(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    R_Model *RETVAL;
    RETVAL = R_model_from_file(path);
    XL_pushnewpptypeuv(L, RETVAL, "R_Model", 0);
    return 1;
}

static int r_model_method_gc_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype_nullable(L, 1, "R_Model"));
    R_model_decref(self);
    return 0;
}

static int r_model_refs_index_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_model_mesh_count_index_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    int RETVAL;
    RETVAL = self->mesh.count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_model_root_node_index_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    R_Node *RETVAL;
    RETVAL = R_node_incref(self->root_node);
    XL_pushnewpptypeuv(L, RETVAL, "R_Node", 0);
    return 1;
}

static int r_model_method_mesh_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    int index = XL_checkint(L, 2);
    R_Mesh *RETVAL;
    if (index > 0 && index <= self->mesh.count) {
        RETVAL = R_mesh_incref(self->mesh.values[index - 1]);
    }
    else {
        R_LUA_DIE(L, "Model mesh index %d out of bounds [1, %d]",
                  index, self->mesh.count);
    }
    XL_pushnewpptypeuv(L, RETVAL, "R_Mesh", 0);
    return 1;
}

static int r_model_method_dump_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    const char *RETVAL;
    char *s = R_model_dump(self);
    RETVAL = s;
    lua_pushstring(L, RETVAL);
    free(s);
    return 1;
}

#ifdef __cplusplus
extern "C" {
#endif

static int r_mesh_index_anchor_xl;
static int r_mesh_index_xl(lua_State *L)
{
    return XL_index(L, "R_Mesh", &r_mesh_index_anchor_xl, 1, 2);
}

static int r_meshbuffer_index_anchor_xl;
static int r_meshbuffer_index_xl(lua_State *L)
{
    if (lua_isinteger(L, 2)) {
        return r_meshbuffer_intindex_xl(L);
    }
    return XL_index(L, "R_MeshBuffer", &r_meshbuffer_index_anchor_xl, 1, 2);
}

static int r_model_index_anchor_xl;
static int r_model_index_xl(lua_State *L)
{
    return XL_index(L, "R_Model", &r_model_index_anchor_xl, 1, 2);
}

static int r_node_index_anchor_xl;
static int r_node_index_xl(lua_State *L)
{
    return XL_index(L, "R_Node", &r_node_index_anchor_xl, 1, 2);
}

int r_meshbuffer_newindex_anchor_xl;
static int r_meshbuffer_newindex_xl(lua_State *L)
{
    if (lua_isinteger(L, 2)) {
        return r_meshbuffer_intnewindex_xl(L);
    }
    return XL_newindex(L, "R_MeshBuffer", &r_meshbuffer_newindex_anchor_xl, 1, 2, 3);
}

static luaL_Reg r_meshbuffer_function_registry_xl[] = {
    {"new", r_meshbuffer_new_xl},
    {NULL, NULL},
};

static luaL_Reg r_model_function_registry_xl[] = {
    {"from_file", r_model_from_file_xl},
    {NULL, NULL},
};

static luaL_Reg r_mesh_index_registry_xl[] = {
    {"buffer_count", r_mesh_buffer_count_index_xl},
    {"refs", r_mesh_refs_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_meshbuffer_index_registry_xl[] = {
    {"count", r_meshbuffer_count_index_xl},
    {"divisor", r_meshbuffer_divisor_index_xl},
    {"name", r_meshbuffer_name_index_xl},
    {"refs", r_meshbuffer_refs_index_xl},
    {"type", r_meshbuffer_type_index_xl},
    {"type_name", r_meshbuffer_type_name_index_xl},
    {"values", r_meshbuffer_values_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_model_index_registry_xl[] = {
    {"mesh_count", r_model_mesh_count_index_xl},
    {"refs", r_model_refs_index_xl},
    {"root_node", r_model_root_node_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_node_index_registry_xl[] = {
    {"child_count", r_node_child_count_index_xl},
    {"mesh_count", r_node_mesh_count_index_xl},
    {"name", r_node_name_index_xl},
    {"refs", r_node_refs_index_xl},
    {"transform", r_node_transform_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_mesh_method_registry_xl[] = {
    {"__gc", r_mesh_method_gc_xl},
    {"__index", r_mesh_index_xl},
    {"buffer", r_mesh_method_buffer_xl},
    {NULL, NULL},
};

static luaL_Reg r_meshbuffer_method_registry_xl[] = {
    {"__gc", r_meshbuffer_method_gc_xl},
    {"__index", r_meshbuffer_index_xl},
    {"__newindex", r_meshbuffer_newindex_xl},
    {NULL, NULL},
};

static luaL_Reg r_model_method_registry_xl[] = {
    {"__gc", r_model_method_gc_xl},
    {"__index", r_model_index_xl},
    {"dump", r_model_method_dump_xl},
    {"mesh", r_model_method_mesh_xl},
    {NULL, NULL},
};

static luaL_Reg r_node_method_registry_xl[] = {
    {"__gc", r_node_method_gc_xl},
    {"__index", r_node_index_xl},
    {"child", r_node_method_child_xl},
    {"mesh", r_node_method_mesh_xl},
    {NULL, NULL},
};

static luaL_Reg r_meshbuffer_newindex_registry_xl[] = {
    {"values", r_meshbuffer_values_newindex_xl},
    {NULL, NULL},
};

int R_lua_model_init(lua_State *L)
{
    XL_initmetatable(L, "R_Mesh", r_mesh_method_registry_xl);
    XL_initmetatable(L, "R_MeshBuffer", r_meshbuffer_method_registry_xl);
    XL_initmetatable(L, "R_Model", r_model_method_registry_xl);
    XL_initmetatable(L, "R_Node", r_node_method_registry_xl);
    XL_initindextable(L, &r_mesh_index_anchor_xl, r_mesh_index_registry_xl);
    XL_initindextable(L, &r_meshbuffer_index_anchor_xl, r_meshbuffer_index_registry_xl);
    XL_initindextable(L, &r_model_index_anchor_xl, r_model_index_registry_xl);
    XL_initindextable(L, &r_node_index_anchor_xl, r_node_index_registry_xl);
    XL_initnewindextable(L, &r_meshbuffer_newindex_anchor_xl, r_meshbuffer_newindex_registry_xl);
    XL_initfunctions(L, r_meshbuffer_function_registry_xl, "R", "MeshBuffer", (const char *)NULL);
    XL_initfunctions(L, r_model_function_registry_xl, "R", "Model", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
