/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2021 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_meshbuffer_method_gc_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype_nullable(L, 1, "R_MeshBuffer"));
    R_mesh_buffer_decref(self);
    return 0;
}

static int r_meshbuffer_refs_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_meshbuffer_name_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    const char *RETVAL;
    RETVAL = self->name;
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_meshbuffer_count_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    int RETVAL;
    RETVAL = self->count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_meshbuffer_divisor_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    int RETVAL;
    RETVAL = self->divisor;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_meshbuffer_type_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    lua_Integer RETVAL;
    RETVAL = (lua_Integer) self->type;
    lua_pushinteger(L, RETVAL);
    return 1;
}

static int r_meshbuffer_type_name_index_xl(lua_State *L)
{
    R_MeshBuffer *self = R_CPPCAST(R_MeshBuffer *, XL_checkpptype(L, 1, "R_MeshBuffer"));
    const char *RETVAL;
    switch (self->type) {
        case R_BUFFER_TYPE_USHORT:
            RETVAL = "ushort";
            break;
        case R_BUFFER_TYPE_FLOAT:
            RETVAL = "float";
            break;
        default:
            RETVAL = "unknown";
            break;
    }
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_mesh_method_gc_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype_nullable(L, 1, "R_Mesh"));
    R_mesh_decref(self);
    return 0;
}

static int r_mesh_refs_index_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype(L, 1, "R_Mesh"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_mesh_buffer_count_index_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype(L, 1, "R_Mesh"));
    int RETVAL;
    RETVAL = self->buffer.count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_mesh_method_buffer_xl(lua_State *L)
{
    R_Mesh *self = R_CPPCAST(R_Mesh *, XL_checkpptype(L, 1, "R_Mesh"));
    R_MeshBuffer *RETVAL;
    int type = lua_type(L, 2);
    if (type == LUA_TNUMBER) {
        int index = XL_checkint(L, 2);
        if (index > 0 && index <= self->buffer.count) {
            RETVAL = R_mesh_buffer_incref(self->buffer.values[index - 1]);
        }
        else {
            R_LUA_DIE(L, "Mesh buffer index %d out of bounds [1, %d]",
                      self->buffer.count);
        }
    }
    else if (type == LUA_TSTRING) {
        const char *name = lua_tostring(L, 2);
        int index = R_mesh_buffer_index_by_name(self, name);
        if (index >= 0) {
            RETVAL = R_mesh_buffer_incref(self->buffer.values[index]);
        }
        else {
            R_LUA_DIE(L, "Mesh buffer with name '%s' not found", name);
        }
    }
    else {
        R_LUA_DIE(L, "Can't get a mesh buffer by a %s", lua_typename(L, type));
    }
    XL_pushnewpptypeuv(L, RETVAL, "R_MeshBuffer", 0);
    return 1;
}

static int r_model_from_file_xl(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    R_Model *RETVAL;
    RETVAL = R_model_from_file(path);
    XL_pushnewpptypeuv(L, RETVAL, "R_Model", 0);
    return 1;
}

static int r_model_method_gc_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype_nullable(L, 1, "R_Model"));
    R_model_decref(self);
    return 0;
}

static int r_model_refs_index_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_model_mesh_count_index_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    int RETVAL;
    RETVAL = self->mesh.count;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_model_method_mesh_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    int index = XL_checkint(L, 2);
    R_Mesh *RETVAL;
    if (index > 0 && index <= self->mesh.count) {
        RETVAL = R_mesh_incref(self->mesh.values[index - 1]);
    }
    else {
        R_LUA_DIE(L, "Mesh index %d out of bounds [1, %d]", self->mesh.count);
    }
    XL_pushnewpptypeuv(L, RETVAL, "R_Mesh", 0);
    return 1;
}

static int r_model_method_dump_xl(lua_State *L)
{
    R_Model *self = R_CPPCAST(R_Model *, XL_checkpptype(L, 1, "R_Model"));
    const char *RETVAL;
    char *s = R_model_dump(self);
    RETVAL = s;
    lua_pushstring(L, RETVAL);
    free(s);
    return 1;
}

#ifdef __cplusplus
extern "C" {
#endif

static int r_mesh_index_anchor_xl;
static int r_mesh_index_xl(lua_State *L)
{
    return XL_index(L, "R_Mesh", &r_mesh_index_anchor_xl, 1, 2);
}

static int r_meshbuffer_index_anchor_xl;
static int r_meshbuffer_index_xl(lua_State *L)
{
    return XL_index(L, "R_MeshBuffer", &r_meshbuffer_index_anchor_xl, 1, 2);
}

static int r_model_index_anchor_xl;
static int r_model_index_xl(lua_State *L)
{
    return XL_index(L, "R_Model", &r_model_index_anchor_xl, 1, 2);
}

static luaL_Reg r_model_function_registry_xl[] = {
    {"from_file", r_model_from_file_xl},
    {NULL, NULL},
};

static luaL_Reg r_mesh_index_registry_xl[] = {
    {"buffer_count", r_mesh_buffer_count_index_xl},
    {"refs", r_mesh_refs_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_meshbuffer_index_registry_xl[] = {
    {"count", r_meshbuffer_count_index_xl},
    {"divisor", r_meshbuffer_divisor_index_xl},
    {"name", r_meshbuffer_name_index_xl},
    {"refs", r_meshbuffer_refs_index_xl},
    {"type", r_meshbuffer_type_index_xl},
    {"type_name", r_meshbuffer_type_name_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_model_index_registry_xl[] = {
    {"mesh_count", r_model_mesh_count_index_xl},
    {"refs", r_model_refs_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_mesh_method_registry_xl[] = {
    {"__gc", r_mesh_method_gc_xl},
    {"__index", r_mesh_index_xl},
    {"buffer", r_mesh_method_buffer_xl},
    {NULL, NULL},
};

static luaL_Reg r_meshbuffer_method_registry_xl[] = {
    {"__gc", r_meshbuffer_method_gc_xl},
    {"__index", r_meshbuffer_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_model_method_registry_xl[] = {
    {"__gc", r_model_method_gc_xl},
    {"__index", r_model_index_xl},
    {"dump", r_model_method_dump_xl},
    {"mesh", r_model_method_mesh_xl},
    {NULL, NULL},
};

int R_lua_model_init(lua_State *L)
{
    XL_initmetatable(L, "R_Mesh", r_mesh_method_registry_xl);
    XL_initmetatable(L, "R_MeshBuffer", r_meshbuffer_method_registry_xl);
    XL_initmetatable(L, "R_Model", r_model_method_registry_xl);
    XL_initindextable(L, &r_mesh_index_anchor_xl, r_mesh_index_registry_xl);
    XL_initindextable(L, &r_meshbuffer_index_anchor_xl, r_meshbuffer_index_registry_xl);
    XL_initindextable(L, &r_model_index_anchor_xl, r_model_index_registry_xl);
    XL_initfunctions(L, r_model_function_registry_xl, "R", "Model", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
