/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2020 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_sample_from_file_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    const char *path = luaL_checkstring(L, 1);
    R_Sample *RETVAL;
    RETVAL = R_sample_from_file(path);
    XL_pushnewpptypeuv(L, RETVAL, "R_Sample", 0);
    return 1;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

static int r_sample_method_gc_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    R_Sample *self = R_CPPCAST(R_Sample *, XL_checkpptype_nullable(L, 1, "R_Sample"));
    R_sample_free(self);
    return 0;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

static int r_sample_len_index_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    R_Sample *self = R_CPPCAST(R_Sample *, XL_checkpptype(L, 1, "R_Sample"));
    int RETVAL;
    RETVAL = self->len;
    XL_pushint(L, RETVAL);
    return 1;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

static int r_sample_channels_index_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    R_Sample *self = R_CPPCAST(R_Sample *, XL_checkpptype(L, 1, "R_Sample"));
    int RETVAL;
    RETVAL = self->channels;
    XL_pushint(L, RETVAL);
    return 1;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

static int r_sample_rate_index_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    R_Sample *self = R_CPPCAST(R_Sample *, XL_checkpptype(L, 1, "R_Sample"));
    int RETVAL;
    RETVAL = self->rate;
    XL_pushint(L, RETVAL);
    return 1;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

static int r_sample_al_format_index_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    R_Sample *self = R_CPPCAST(R_Sample *, XL_checkpptype(L, 1, "R_Sample"));
    int RETVAL;
    RETVAL = R_sample_al_format(self);
    XL_pushint(L, RETVAL);
    return 1;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

static int r_sample_al_buffer_size_index_xl(lua_State *L)
{
#ifdef ROUSE_AL_ENABLED
    R_Sample *self = R_CPPCAST(R_Sample *, XL_checkpptype(L, 1, "R_Sample"));
    int RETVAL;
    RETVAL = R_sample_al_buffer_size(self);
    XL_pushint(L, RETVAL);
    return 1;
#else
    R_LUA_DIE(L, "OpenAL not compiled in")
#endif
}

#ifdef __cplusplus
extern "C" {
#endif

static int r_sample_index_dummy_xl;
static int r_sample_index_xl(lua_State *L)
{
    return XL_index(L, "R_Sample", &r_sample_index_dummy_xl, 1, 2);
}

static luaL_Reg r_sample_function_registry_xl[] = {
    {"from_file", r_sample_from_file_xl},
    {NULL, NULL},
};

static luaL_Reg r_sample_index_registry_xl[] = {
    {"al_buffer_size", r_sample_al_buffer_size_index_xl},
    {"al_format", r_sample_al_format_index_xl},
    {"channels", r_sample_channels_index_xl},
    {"len", r_sample_len_index_xl},
    {"rate", r_sample_rate_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_sample_method_registry_xl[] = {
    {"__gc", r_sample_method_gc_xl},
    {"__index", r_sample_index_xl},
    {NULL, NULL},
};

int R_lua_sample_init(lua_State *L)
{
    XL_initmetatable(L, "R_Sample", r_sample_method_registry_xl);
    XL_initindextable(L, &r_sample_index_dummy_xl, r_sample_index_registry_xl);
    XL_initfunctions(L, r_sample_function_registry_xl, "R", "Sample", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
