/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int sdl_ticks_staticindex_xl(lua_State *L)
{
    uint32_t RETVAL;
    RETVAL = SDL_GetTicks();
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_get_ticks_xl(lua_State *L)
{
    uint32_t RETVAL;
    R_LUA_WARN_ON_DEPRECATED_GETTER("SDL.ticks");
    RETVAL = SDL_GetTicks();
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_window_flags_staticindex_xl(lua_State *L)
{
    uint32_t RETVAL;
    RETVAL = SDL_GetWindowFlags(R_window);
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_get_window_flags_xl(lua_State *L)
{
    uint32_t RETVAL;
    R_LUA_WARN_ON_DEPRECATED_GETTER("SDL.window_flags");
    RETVAL = SDL_GetWindowFlags(R_window);
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_set_windowed_xl(lua_State *L)
{
    XL_UNUSED(L);
    SDL_SetWindowFullscreen(R_window, 0);
    return 0;
}

static int sdl_set_fullscreen_xl(lua_State *L)
{
    XL_UNUSED(L);
    SDL_SetWindowFullscreen(R_window, SDL_WINDOW_FULLSCREEN);
    return 0;
}

static int sdl_set_fullscreen_desktop_xl(lua_State *L)
{
    XL_UNUSED(L);
    SDL_SetWindowFullscreen(R_window, SDL_WINDOW_FULLSCREEN_DESKTOP);
    return 0;
}

#define ANY_FULLSCREEN \
    (SDL_WINDOW_FULLSCREEN | SDL_WINDOW_FULLSCREEN_DESKTOP)

static void toggle_window(uint32_t flags)
{
    bool is_fullscreen = SDL_GetWindowFlags(R_window) & ANY_FULLSCREEN;
    SDL_SetWindowFullscreen(R_window, is_fullscreen ? 0 : flags);
}

static int sdl_toggle_fullscreen_xl(lua_State *L)
{
    XL_UNUSED(L);
    toggle_window(SDL_WINDOW_FULLSCREEN);
    return 0;
}

static int sdl_toggle_fullscreen_desktop_xl(lua_State *L)
{
    XL_UNUSED(L);
    toggle_window(SDL_WINDOW_FULLSCREEN_DESKTOP);
    return 0;
}

static int sdl_gl_swap_interval_staticindex_xl(lua_State *L)
{
    int RETVAL;
    RETVAL = SDL_GL_GetSwapInterval();
    XL_pushint(L, RETVAL);
    return 1;
}

static int sdl_get_gl_swap_interval_xl(lua_State *L)
{
    int RETVAL;
    R_LUA_WARN_ON_DEPRECATED_GETTER("SDL.gl_swap_interval");
    RETVAL = SDL_GL_GetSwapInterval();
    XL_pushint(L, RETVAL);
    return 1;
}

static int sdl_gl_swap_interval_staticnewindex_xl(lua_State *L)
{
    int VALUE = XL_checkint(L, 1);
    if (SDL_GL_SetSwapInterval(VALUE) != 0) {
        R_LUA_DIE(L, "Can't set GL swap interval to %d: %s",
                  VALUE, SDL_GetError());
    }
    return 0;
}

static int sdl_set_gl_swap_interval_xl(lua_State *L)
{
    int interval = XL_checkint(L, 1);
    R_LUA_WARN_ON_DEPRECATED_SETTER("SDL.gl_swap_interval");
    if (SDL_GL_SetSwapInterval(interval) != 0) {
        R_LUA_DIE(L, "Can't set GL swap interval to %d: %s",
                  interval, SDL_GetError());
    }
    return 0;
}

static int sdl_windowevent_type_index_xl(lua_State *L)
{
    SDL_WindowEvent *self = XL_checkutype(L, 1, "SDL_WindowEvent");
    uint32_t RETVAL;
    RETVAL = self->type;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_windowevent_timestamp_index_xl(lua_State *L)
{
    SDL_WindowEvent *self = XL_checkutype(L, 1, "SDL_WindowEvent");
    uint32_t RETVAL;
    RETVAL = self->timestamp;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_windowevent_window_id_index_xl(lua_State *L)
{
    SDL_WindowEvent *self = XL_checkutype(L, 1, "SDL_WindowEvent");
    uint32_t RETVAL;
    RETVAL = self->windowID;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_windowevent_event_index_xl(lua_State *L)
{
    SDL_WindowEvent *self = XL_checkutype(L, 1, "SDL_WindowEvent");
    uint8_t RETVAL;
    RETVAL = self->event;
    XL_pushuint8(L, RETVAL);
    return 1;
}

static int sdl_windowevent_data1_index_xl(lua_State *L)
{
    SDL_WindowEvent *self = XL_checkutype(L, 1, "SDL_WindowEvent");
    int32_t RETVAL;
    RETVAL = self->data1;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_windowevent_data2_index_xl(lua_State *L)
{
    SDL_WindowEvent *self = XL_checkutype(L, 1, "SDL_WindowEvent");
    int32_t RETVAL;
    RETVAL = self->data2;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_type_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    uint32_t RETVAL;
    RETVAL = self->type;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_timestamp_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    uint32_t RETVAL;
    RETVAL = self->timestamp;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_window_id_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    uint32_t RETVAL;
    RETVAL = self->windowID;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_state_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    uint8_t RETVAL;
    RETVAL = self->state;
    XL_pushuint8(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_repeat_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    uint8_t RETVAL;
    RETVAL = self->repeat;
    XL_pushuint8(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_scancode_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    lua_Integer RETVAL;
    RETVAL = (lua_Integer) self->keysym.scancode;
    lua_pushinteger(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_sym_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    lua_Integer RETVAL;
    RETVAL = (lua_Integer) self->keysym.sym;
    lua_pushinteger(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_mod_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    lua_Integer RETVAL;
    RETVAL = (lua_Integer) self->keysym.mod;
    lua_pushinteger(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_pressed_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    bool RETVAL;
    RETVAL = self->state == SDL_PRESSED;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_keyboardevent_released_index_xl(lua_State *L)
{
    SDL_KeyboardEvent *self = XL_checkutype(L, 1, "SDL_KeyboardEvent");
    bool RETVAL;
    RETVAL = self->state == SDL_RELEASED;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_type_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    uint32_t RETVAL;
    RETVAL = self->type;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_timestamp_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    uint32_t RETVAL;
    RETVAL = self->timestamp;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_window_id_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    uint32_t RETVAL;
    RETVAL = self->windowID;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_which_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    uint32_t RETVAL;
    RETVAL = self->which;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_state_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    uint32_t RETVAL;
    RETVAL = self->state;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_x_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    int32_t RETVAL;
    RETVAL = self->x;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_y_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    int32_t RETVAL;
    RETVAL = self->y;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_xrel_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    int32_t RETVAL;
    RETVAL = self->xrel;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_yrel_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    int32_t RETVAL;
    RETVAL = self->yrel;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_left_button_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    bool RETVAL;
    RETVAL = self->state | SDL_BUTTON_LMASK;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_middle_button_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    bool RETVAL;
    RETVAL = self->state | SDL_BUTTON_MMASK;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_right_button_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    bool RETVAL;
    RETVAL = self->state | SDL_BUTTON_RMASK;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_x1_button_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    bool RETVAL;
    RETVAL = self->state | SDL_BUTTON_X1MASK;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousemotionevent_x2_button_index_xl(lua_State *L)
{
    SDL_MouseMotionEvent *self = XL_checkutype(L, 1, "SDL_MouseMotionEvent");
    bool RETVAL;
    RETVAL = self->state | SDL_BUTTON_X2MASK;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_type_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    uint32_t RETVAL;
    RETVAL = self->type;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_timestamp_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    uint32_t RETVAL;
    RETVAL = self->timestamp;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_window_id_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    uint32_t RETVAL;
    RETVAL = self->windowID;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_which_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    uint32_t RETVAL;
    RETVAL = self->which;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_button_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    uint8_t RETVAL;
    RETVAL = self->button;
    XL_pushuint8(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_state_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    uint8_t RETVAL;
    RETVAL = self->state;
    XL_pushuint8(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_x_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    int32_t RETVAL;
    RETVAL = self->x;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_y_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    int32_t RETVAL;
    RETVAL = self->y;
    XL_pushint32(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_pressed_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->state == SDL_PRESSED;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_released_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->state == SDL_RELEASED;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_left_button_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->button == SDL_BUTTON_LEFT;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_middle_button_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->button == SDL_BUTTON_MIDDLE;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_right_button_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->button == SDL_BUTTON_RIGHT;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_x1_button_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->button == SDL_BUTTON_X1;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_mousebuttonevent_x2_button_index_xl(lua_State *L)
{
    SDL_MouseButtonEvent *self = XL_checkutype(L, 1, "SDL_MouseButtonEvent");
    bool RETVAL;
    RETVAL = self->button == SDL_BUTTON_X2;
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int sdl_event_type_index_xl(lua_State *L)
{
    SDL_Event *self = XL_checkutype(L, 1, "SDL_Event");
    uint32_t RETVAL;
    RETVAL = self->type;
    XL_pushuint32(L, RETVAL);
    return 1;
}

static int sdl_event_timestamp_index_xl(lua_State *L)
{
    SDL_Event *self = XL_checkutype(L, 1, "SDL_Event");
    uint32_t RETVAL;
    RETVAL = self->common.timestamp;
    XL_pushuint32(L, RETVAL);
    return 1;
}


static bool is_allowed_event_type(uint32_t type, int len,
                                  const uint32_t allowed[static len])
{
    for (int i = 0; i < len; ++i) {
        if (type == allowed[i]) {
            return true;
        }
    }
    return false;
}

static noreturn void error_on_event_type(lua_State *L, const char *field,
                                         uint32_t type)
{
    luaL_error(L, "Can't access %s event data on event of type %d",
               field, (int) type);
    R_UNREACHABLE();
}

#define GET_IN_EVENT_UNION(FIELD, ...) \
    static const uint32_t allowed[] = {__VA_ARGS__}; \
    uint32_t type = self->type; \
    if (is_allowed_event_type(type, R_size2int(R_LENGTH(allowed)), allowed)) { \
        RETVAL = self->FIELD; \
    } \
    else { \
        error_on_event_type(L, #FIELD, type); \
    }


static int sdl_event_window_index_xl(lua_State *L)
{
    SDL_Event *self = XL_checkutype(L, 1, "SDL_Event");
    SDL_WindowEvent RETVAL;
    GET_IN_EVENT_UNION(window, SDL_WINDOWEVENT);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(SDL_WindowEvent), "SDL_WindowEvent", 0);
    return 1;
}

static int sdl_event_key_index_xl(lua_State *L)
{
    SDL_Event *self = XL_checkutype(L, 1, "SDL_Event");
    SDL_KeyboardEvent RETVAL;
    GET_IN_EVENT_UNION(key, SDL_KEYDOWN, SDL_KEYUP);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(SDL_KeyboardEvent), "SDL_KeyboardEvent", 0);
    return 1;
}

static int sdl_event_motion_index_xl(lua_State *L)
{
    SDL_Event *self = XL_checkutype(L, 1, "SDL_Event");
    SDL_MouseMotionEvent RETVAL;
    GET_IN_EVENT_UNION(motion, SDL_MOUSEMOTION);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(SDL_MouseMotionEvent), "SDL_MouseMotionEvent", 0);
    return 1;
}

static int sdl_event_button_index_xl(lua_State *L)
{
    SDL_Event *self = XL_checkutype(L, 1, "SDL_Event");
    SDL_MouseButtonEvent RETVAL;
    GET_IN_EVENT_UNION(button, SDL_MOUSEBUTTONDOWN, SDL_MOUSEBUTTONUP);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(SDL_MouseButtonEvent), "SDL_MouseButtonEvent", 0);
    return 1;
}

static SDL_Cursor *get_system_cursor(lua_State *L, lua_Integer i)
{
    static SDL_Cursor *cursors[SDL_NUM_SYSTEM_CURSORS];
    if (i >= 0 && i < SDL_NUM_SYSTEM_CURSORS) {
        SDL_Cursor *cursor = cursors[i];
        if (!cursor) {
            cursor = cursors[i] = SDL_CreateSystemCursor((SDL_SystemCursor) i);
        }
        return cursor;
    }
    else {
        R_LUA_DIE(L, "Bad system cursor index: %d", i);
    }
}

static int sdl_cursor_staticnewindex_xl(lua_State *L)
{
    luaL_checkany(L, 1);
    int VALUE = 1;
    SDL_Cursor *cursor = lua_isnil(L, VALUE)
                       ? SDL_GetDefaultCursor()
                       : get_system_cursor(L, luaL_checkinteger(L, VALUE));
    if (cursor) {
        SDL_SetCursor(cursor);
    }
    return 0;
}

static int sdl_event_index_dummy_xl;
static int sdl_event_index_xl(lua_State *L)
{
    return XL_index(L, "SDL_Event", &sdl_event_index_dummy_xl, 1, 2);
}

static int sdl_keyboardevent_index_dummy_xl;
static int sdl_keyboardevent_index_xl(lua_State *L)
{
    return XL_index(L, "SDL_KeyboardEvent", &sdl_keyboardevent_index_dummy_xl, 1, 2);
}

static int sdl_mousebuttonevent_index_dummy_xl;
static int sdl_mousebuttonevent_index_xl(lua_State *L)
{
    return XL_index(L, "SDL_MouseButtonEvent", &sdl_mousebuttonevent_index_dummy_xl, 1, 2);
}

static int sdl_mousemotionevent_index_dummy_xl;
static int sdl_mousemotionevent_index_xl(lua_State *L)
{
    return XL_index(L, "SDL_MouseMotionEvent", &sdl_mousemotionevent_index_dummy_xl, 1, 2);
}

static int sdl_windowevent_index_dummy_xl;
static int sdl_windowevent_index_xl(lua_State *L)
{
    return XL_index(L, "SDL_WindowEvent", &sdl_windowevent_index_dummy_xl, 1, 2);
}

static int sdl_staticindex_dummy_xl;
static int sdl_staticindex_xl(lua_State *L)
{
    return XL_staticindex(L, &sdl_staticindex_dummy_xl, 2);
}

static int sdl_staticnewindex_dummy_xl;
static int sdl_staticnewindex_xl(lua_State *L)
{
    return XL_staticnewindex(L, &sdl_staticnewindex_dummy_xl, 1, 2, 3);
}

static luaL_Reg sdl_function_registry_xl[] = {
    {"__index", sdl_staticindex_xl},
    {"__newindex", sdl_staticnewindex_xl},
    {"get_gl_swap_interval", sdl_get_gl_swap_interval_xl},
    {"get_ticks", sdl_get_ticks_xl},
    {"get_window_flags", sdl_get_window_flags_xl},
    {"set_fullscreen", sdl_set_fullscreen_xl},
    {"set_fullscreen_desktop", sdl_set_fullscreen_desktop_xl},
    {"set_gl_swap_interval", sdl_set_gl_swap_interval_xl},
    {"set_windowed", sdl_set_windowed_xl},
    {"toggle_fullscreen", sdl_toggle_fullscreen_xl},
    {"toggle_fullscreen_desktop", sdl_toggle_fullscreen_desktop_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_event_index_registry_xl[] = {
    {"button", sdl_event_button_index_xl},
    {"key", sdl_event_key_index_xl},
    {"motion", sdl_event_motion_index_xl},
    {"timestamp", sdl_event_timestamp_index_xl},
    {"type", sdl_event_type_index_xl},
    {"window", sdl_event_window_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_keyboardevent_index_registry_xl[] = {
    {"mod", sdl_keyboardevent_mod_index_xl},
    {"pressed", sdl_keyboardevent_pressed_index_xl},
    {"released", sdl_keyboardevent_released_index_xl},
    {"repeat", sdl_keyboardevent_repeat_index_xl},
    {"scancode", sdl_keyboardevent_scancode_index_xl},
    {"state", sdl_keyboardevent_state_index_xl},
    {"sym", sdl_keyboardevent_sym_index_xl},
    {"timestamp", sdl_keyboardevent_timestamp_index_xl},
    {"type", sdl_keyboardevent_type_index_xl},
    {"window_id", sdl_keyboardevent_window_id_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_mousebuttonevent_index_registry_xl[] = {
    {"button", sdl_mousebuttonevent_button_index_xl},
    {"left_button", sdl_mousebuttonevent_left_button_index_xl},
    {"middle_button", sdl_mousebuttonevent_middle_button_index_xl},
    {"pressed", sdl_mousebuttonevent_pressed_index_xl},
    {"released", sdl_mousebuttonevent_released_index_xl},
    {"right_button", sdl_mousebuttonevent_right_button_index_xl},
    {"state", sdl_mousebuttonevent_state_index_xl},
    {"timestamp", sdl_mousebuttonevent_timestamp_index_xl},
    {"type", sdl_mousebuttonevent_type_index_xl},
    {"which", sdl_mousebuttonevent_which_index_xl},
    {"window_id", sdl_mousebuttonevent_window_id_index_xl},
    {"x", sdl_mousebuttonevent_x_index_xl},
    {"x1_button", sdl_mousebuttonevent_x1_button_index_xl},
    {"x2_button", sdl_mousebuttonevent_x2_button_index_xl},
    {"y", sdl_mousebuttonevent_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_mousemotionevent_index_registry_xl[] = {
    {"left_button", sdl_mousemotionevent_left_button_index_xl},
    {"middle_button", sdl_mousemotionevent_middle_button_index_xl},
    {"right_button", sdl_mousemotionevent_right_button_index_xl},
    {"state", sdl_mousemotionevent_state_index_xl},
    {"timestamp", sdl_mousemotionevent_timestamp_index_xl},
    {"type", sdl_mousemotionevent_type_index_xl},
    {"which", sdl_mousemotionevent_which_index_xl},
    {"window_id", sdl_mousemotionevent_window_id_index_xl},
    {"x", sdl_mousemotionevent_x_index_xl},
    {"x1_button", sdl_mousemotionevent_x1_button_index_xl},
    {"x2_button", sdl_mousemotionevent_x2_button_index_xl},
    {"xrel", sdl_mousemotionevent_xrel_index_xl},
    {"y", sdl_mousemotionevent_y_index_xl},
    {"yrel", sdl_mousemotionevent_yrel_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_windowevent_index_registry_xl[] = {
    {"data1", sdl_windowevent_data1_index_xl},
    {"data2", sdl_windowevent_data2_index_xl},
    {"event", sdl_windowevent_event_index_xl},
    {"timestamp", sdl_windowevent_timestamp_index_xl},
    {"type", sdl_windowevent_type_index_xl},
    {"window_id", sdl_windowevent_window_id_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_event_method_registry_xl[] = {
    {"__index", sdl_event_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_keyboardevent_method_registry_xl[] = {
    {"__index", sdl_keyboardevent_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_mousebuttonevent_method_registry_xl[] = {
    {"__index", sdl_mousebuttonevent_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_mousemotionevent_method_registry_xl[] = {
    {"__index", sdl_mousemotionevent_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_windowevent_method_registry_xl[] = {
    {"__index", sdl_windowevent_index_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_staticindex_registry_xl[] = {
    {"gl_swap_interval", sdl_gl_swap_interval_staticindex_xl},
    {"ticks", sdl_ticks_staticindex_xl},
    {"window_flags", sdl_window_flags_staticindex_xl},
    {NULL, NULL},
};

static luaL_Reg sdl_staticnewindex_registry_xl[] = {
    {"cursor", sdl_cursor_staticnewindex_xl},
    {"gl_swap_interval", sdl_gl_swap_interval_staticnewindex_xl},
    {NULL, NULL},
};

static XL_EnumEntry sdl_window_enum_xl[] = {
    {"FULLSCREEN", (lua_Integer) SDL_WINDOW_FULLSCREEN},
    {"OPENGL", (lua_Integer) SDL_WINDOW_OPENGL},
    {"SHOWN", (lua_Integer) SDL_WINDOW_SHOWN},
    {"HIDDEN", (lua_Integer) SDL_WINDOW_HIDDEN},
    {"BORDERLESS", (lua_Integer) SDL_WINDOW_BORDERLESS},
    {"RESIZABLE", (lua_Integer) SDL_WINDOW_RESIZABLE},
    {"MINIMIZED", (lua_Integer) SDL_WINDOW_MINIMIZED},
    {"MAXIMIZED", (lua_Integer) SDL_WINDOW_MAXIMIZED},
    {"INPUT_GRABBED", (lua_Integer) SDL_WINDOW_INPUT_GRABBED},
    {"INPUT_FOCUS", (lua_Integer) SDL_WINDOW_INPUT_FOCUS},
    {"MOUSE_FOCUS", (lua_Integer) SDL_WINDOW_MOUSE_FOCUS},
    {"FULLSCREEN_DESKTOP", (lua_Integer) SDL_WINDOW_FULLSCREEN_DESKTOP},
    {"FOREIGN", (lua_Integer) SDL_WINDOW_FOREIGN},
    {"ALLOW_HIGHDPI", (lua_Integer) SDL_WINDOW_ALLOW_HIGHDPI},
    {"MOUSE_CAPTURE", (lua_Integer) SDL_WINDOW_MOUSE_CAPTURE},
    {"ALWAYS_ON_TOP", (lua_Integer) SDL_WINDOW_ALWAYS_ON_TOP},
    {"SKIP_TASKBAR", (lua_Integer) SDL_WINDOW_SKIP_TASKBAR},
    {"UTILITY", (lua_Integer) SDL_WINDOW_UTILITY},
    {"TOOLTIP", (lua_Integer) SDL_WINDOW_TOOLTIP},
    {"POPUP_MENU", (lua_Integer) SDL_WINDOW_POPUP_MENU},
    {"VULKAN", (lua_Integer) SDL_WINDOW_VULKAN},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_eventtype_enum_xl[] = {
    {"QUIT", (lua_Integer) SDL_QUIT},
    {"APP_TERMINATING", (lua_Integer) SDL_APP_TERMINATING},
    {"APP_LOWMEMORY", (lua_Integer) SDL_APP_LOWMEMORY},
    {"APP_WILLENTERBACKGROUND", (lua_Integer) SDL_APP_WILLENTERBACKGROUND},
    {"APP_DIDENTERBACKGROUND", (lua_Integer) SDL_APP_DIDENTERBACKGROUND},
    {"APP_WILLENTERFOREGROUND", (lua_Integer) SDL_APP_WILLENTERFOREGROUND},
    {"APP_DIDENTERFOREGROUND", (lua_Integer) SDL_APP_DIDENTERFOREGROUND},
    {"DISPLAYEVENT", (lua_Integer) SDL_DISPLAYEVENT},
    {"WINDOWEVENT", (lua_Integer) SDL_WINDOWEVENT},
    {"SYSWMEVENT", (lua_Integer) SDL_SYSWMEVENT},
    {"KEYDOWN", (lua_Integer) SDL_KEYDOWN},
    {"KEYUP", (lua_Integer) SDL_KEYUP},
    {"TEXTEDITING", (lua_Integer) SDL_TEXTEDITING},
    {"TEXTINPUT", (lua_Integer) SDL_TEXTINPUT},
    {"KEYMAPCHANGED", (lua_Integer) SDL_KEYMAPCHANGED},
    {"MOUSEMOTION", (lua_Integer) SDL_MOUSEMOTION},
    {"MOUSEBUTTONDOWN", (lua_Integer) SDL_MOUSEBUTTONDOWN},
    {"MOUSEBUTTONUP", (lua_Integer) SDL_MOUSEBUTTONUP},
    {"MOUSEWHEEL", (lua_Integer) SDL_MOUSEWHEEL},
    {"JOYAXISMOTION", (lua_Integer) SDL_JOYAXISMOTION},
    {"JOYBALLMOTION", (lua_Integer) SDL_JOYBALLMOTION},
    {"JOYHATMOTION", (lua_Integer) SDL_JOYHATMOTION},
    {"JOYBUTTONDOWN", (lua_Integer) SDL_JOYBUTTONDOWN},
    {"JOYBUTTONUP", (lua_Integer) SDL_JOYBUTTONUP},
    {"JOYDEVICEADDED", (lua_Integer) SDL_JOYDEVICEADDED},
    {"JOYDEVICEREMOVED", (lua_Integer) SDL_JOYDEVICEREMOVED},
    {"CONTROLLERAXISMOTION", (lua_Integer) SDL_CONTROLLERAXISMOTION},
    {"CONTROLLERBUTTONDOWN", (lua_Integer) SDL_CONTROLLERBUTTONDOWN},
    {"CONTROLLERBUTTONUP", (lua_Integer) SDL_CONTROLLERBUTTONUP},
    {"CONTROLLERDEVICEADDED", (lua_Integer) SDL_CONTROLLERDEVICEADDED},
    {"CONTROLLERDEVICEREMOVED", (lua_Integer) SDL_CONTROLLERDEVICEREMOVED},
    {"CONTROLLERDEVICEREMAPPED", (lua_Integer) SDL_CONTROLLERDEVICEREMAPPED},
    {"FINGERDOWN", (lua_Integer) SDL_FINGERDOWN},
    {"FINGERUP", (lua_Integer) SDL_FINGERUP},
    {"FINGERMOTION", (lua_Integer) SDL_FINGERMOTION},
    {"DOLLARGESTURE", (lua_Integer) SDL_DOLLARGESTURE},
    {"DOLLARRECORD", (lua_Integer) SDL_DOLLARRECORD},
    {"MULTIGESTURE", (lua_Integer) SDL_MULTIGESTURE},
    {"CLIPBOARDUPDATE", (lua_Integer) SDL_CLIPBOARDUPDATE},
    {"DROPFILE", (lua_Integer) SDL_DROPFILE},
    {"DROPTEXT", (lua_Integer) SDL_DROPTEXT},
    {"DROPBEGIN", (lua_Integer) SDL_DROPBEGIN},
    {"DROPCOMPLETE", (lua_Integer) SDL_DROPCOMPLETE},
    {"AUDIODEVICEADDED", (lua_Integer) SDL_AUDIODEVICEADDED},
    {"AUDIODEVICEREMOVED", (lua_Integer) SDL_AUDIODEVICEREMOVED},
    {"SENSORUPDATE", (lua_Integer) SDL_SENSORUPDATE},
    {"RENDER_TARGETS_RESET", (lua_Integer) SDL_RENDER_TARGETS_RESET},
    {"RENDER_DEVICE_RESET", (lua_Integer) SDL_RENDER_DEVICE_RESET},
    {"USEREVENT", (lua_Integer) SDL_USEREVENT},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_windoweventtype_enum_xl[] = {
    {"SHOWN", (lua_Integer) SDL_WINDOWEVENT_SHOWN},
    {"HIDDEN", (lua_Integer) SDL_WINDOWEVENT_HIDDEN},
    {"EXPOSED", (lua_Integer) SDL_WINDOWEVENT_EXPOSED},
    {"MOVED", (lua_Integer) SDL_WINDOWEVENT_MOVED},
    {"RESIZED", (lua_Integer) SDL_WINDOWEVENT_RESIZED},
    {"SIZE_CHANGED", (lua_Integer) SDL_WINDOWEVENT_SIZE_CHANGED},
    {"MINIMIZED", (lua_Integer) SDL_WINDOWEVENT_MINIMIZED},
    {"MAXIMIZED", (lua_Integer) SDL_WINDOWEVENT_MAXIMIZED},
    {"RESTORED", (lua_Integer) SDL_WINDOWEVENT_RESTORED},
    {"ENTER", (lua_Integer) SDL_WINDOWEVENT_ENTER},
    {"LEAVE", (lua_Integer) SDL_WINDOWEVENT_LEAVE},
    {"FOCUS_GAINED", (lua_Integer) SDL_WINDOWEVENT_FOCUS_GAINED},
    {"FOCUS_LOST", (lua_Integer) SDL_WINDOWEVENT_FOCUS_LOST},
    {"CLOSE", (lua_Integer) SDL_WINDOWEVENT_CLOSE},
    {"TAKE_FOCUS", (lua_Integer) SDL_WINDOWEVENT_TAKE_FOCUS},
    {"HIT_TEST", (lua_Integer) SDL_WINDOWEVENT_HIT_TEST},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_keyboardevent_state_enum_xl[] = {
    {"PRESSED", (lua_Integer) SDL_PRESSED},
    {"RELEASED", (lua_Integer) SDL_RELEASED},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_scancode_enum_xl[] = {
    {"UNKNOWN", (lua_Integer) SDL_SCANCODE_UNKNOWN},
    {"A", (lua_Integer) SDL_SCANCODE_A},
    {"B", (lua_Integer) SDL_SCANCODE_B},
    {"C", (lua_Integer) SDL_SCANCODE_C},
    {"D", (lua_Integer) SDL_SCANCODE_D},
    {"E", (lua_Integer) SDL_SCANCODE_E},
    {"F", (lua_Integer) SDL_SCANCODE_F},
    {"G", (lua_Integer) SDL_SCANCODE_G},
    {"H", (lua_Integer) SDL_SCANCODE_H},
    {"I", (lua_Integer) SDL_SCANCODE_I},
    {"J", (lua_Integer) SDL_SCANCODE_J},
    {"K", (lua_Integer) SDL_SCANCODE_K},
    {"L", (lua_Integer) SDL_SCANCODE_L},
    {"M", (lua_Integer) SDL_SCANCODE_M},
    {"N", (lua_Integer) SDL_SCANCODE_N},
    {"O", (lua_Integer) SDL_SCANCODE_O},
    {"P", (lua_Integer) SDL_SCANCODE_P},
    {"Q", (lua_Integer) SDL_SCANCODE_Q},
    {"R", (lua_Integer) SDL_SCANCODE_R},
    {"S", (lua_Integer) SDL_SCANCODE_S},
    {"T", (lua_Integer) SDL_SCANCODE_T},
    {"U", (lua_Integer) SDL_SCANCODE_U},
    {"V", (lua_Integer) SDL_SCANCODE_V},
    {"W", (lua_Integer) SDL_SCANCODE_W},
    {"X", (lua_Integer) SDL_SCANCODE_X},
    {"Y", (lua_Integer) SDL_SCANCODE_Y},
    {"Z", (lua_Integer) SDL_SCANCODE_Z},
    {"1", (lua_Integer) SDL_SCANCODE_1},
    {"2", (lua_Integer) SDL_SCANCODE_2},
    {"3", (lua_Integer) SDL_SCANCODE_3},
    {"4", (lua_Integer) SDL_SCANCODE_4},
    {"5", (lua_Integer) SDL_SCANCODE_5},
    {"6", (lua_Integer) SDL_SCANCODE_6},
    {"7", (lua_Integer) SDL_SCANCODE_7},
    {"8", (lua_Integer) SDL_SCANCODE_8},
    {"9", (lua_Integer) SDL_SCANCODE_9},
    {"0", (lua_Integer) SDL_SCANCODE_0},
    {"RETURN", (lua_Integer) SDL_SCANCODE_RETURN},
    {"ESCAPE", (lua_Integer) SDL_SCANCODE_ESCAPE},
    {"BACKSPACE", (lua_Integer) SDL_SCANCODE_BACKSPACE},
    {"TAB", (lua_Integer) SDL_SCANCODE_TAB},
    {"SPACE", (lua_Integer) SDL_SCANCODE_SPACE},
    {"MINUS", (lua_Integer) SDL_SCANCODE_MINUS},
    {"EQUALS", (lua_Integer) SDL_SCANCODE_EQUALS},
    {"LEFTBRACKET", (lua_Integer) SDL_SCANCODE_LEFTBRACKET},
    {"RIGHTBRACKET", (lua_Integer) SDL_SCANCODE_RIGHTBRACKET},
    {"BACKSLASH", (lua_Integer) SDL_SCANCODE_BACKSLASH},
    {"NONUSHASH", (lua_Integer) SDL_SCANCODE_NONUSHASH},
    {"SEMICOLON", (lua_Integer) SDL_SCANCODE_SEMICOLON},
    {"APOSTROPHE", (lua_Integer) SDL_SCANCODE_APOSTROPHE},
    {"GRAVE", (lua_Integer) SDL_SCANCODE_GRAVE},
    {"COMMA", (lua_Integer) SDL_SCANCODE_COMMA},
    {"PERIOD", (lua_Integer) SDL_SCANCODE_PERIOD},
    {"SLASH", (lua_Integer) SDL_SCANCODE_SLASH},
    {"CAPSLOCK", (lua_Integer) SDL_SCANCODE_CAPSLOCK},
    {"F1", (lua_Integer) SDL_SCANCODE_F1},
    {"F2", (lua_Integer) SDL_SCANCODE_F2},
    {"F3", (lua_Integer) SDL_SCANCODE_F3},
    {"F4", (lua_Integer) SDL_SCANCODE_F4},
    {"F5", (lua_Integer) SDL_SCANCODE_F5},
    {"F6", (lua_Integer) SDL_SCANCODE_F6},
    {"F7", (lua_Integer) SDL_SCANCODE_F7},
    {"F8", (lua_Integer) SDL_SCANCODE_F8},
    {"F9", (lua_Integer) SDL_SCANCODE_F9},
    {"F10", (lua_Integer) SDL_SCANCODE_F10},
    {"F11", (lua_Integer) SDL_SCANCODE_F11},
    {"F12", (lua_Integer) SDL_SCANCODE_F12},
    {"PRINTSCREEN", (lua_Integer) SDL_SCANCODE_PRINTSCREEN},
    {"SCROLLLOCK", (lua_Integer) SDL_SCANCODE_SCROLLLOCK},
    {"PAUSE", (lua_Integer) SDL_SCANCODE_PAUSE},
    {"INSERT", (lua_Integer) SDL_SCANCODE_INSERT},
    {"HOME", (lua_Integer) SDL_SCANCODE_HOME},
    {"PAGEUP", (lua_Integer) SDL_SCANCODE_PAGEUP},
    {"DELETE", (lua_Integer) SDL_SCANCODE_DELETE},
    {"END", (lua_Integer) SDL_SCANCODE_END},
    {"PAGEDOWN", (lua_Integer) SDL_SCANCODE_PAGEDOWN},
    {"RIGHT", (lua_Integer) SDL_SCANCODE_RIGHT},
    {"LEFT", (lua_Integer) SDL_SCANCODE_LEFT},
    {"DOWN", (lua_Integer) SDL_SCANCODE_DOWN},
    {"UP", (lua_Integer) SDL_SCANCODE_UP},
    {"NUMLOCKCLEAR", (lua_Integer) SDL_SCANCODE_NUMLOCKCLEAR},
    {"KP_DIVIDE", (lua_Integer) SDL_SCANCODE_KP_DIVIDE},
    {"KP_MULTIPLY", (lua_Integer) SDL_SCANCODE_KP_MULTIPLY},
    {"KP_MINUS", (lua_Integer) SDL_SCANCODE_KP_MINUS},
    {"KP_PLUS", (lua_Integer) SDL_SCANCODE_KP_PLUS},
    {"KP_ENTER", (lua_Integer) SDL_SCANCODE_KP_ENTER},
    {"KP_1", (lua_Integer) SDL_SCANCODE_KP_1},
    {"KP_2", (lua_Integer) SDL_SCANCODE_KP_2},
    {"KP_3", (lua_Integer) SDL_SCANCODE_KP_3},
    {"KP_4", (lua_Integer) SDL_SCANCODE_KP_4},
    {"KP_5", (lua_Integer) SDL_SCANCODE_KP_5},
    {"KP_6", (lua_Integer) SDL_SCANCODE_KP_6},
    {"KP_7", (lua_Integer) SDL_SCANCODE_KP_7},
    {"KP_8", (lua_Integer) SDL_SCANCODE_KP_8},
    {"KP_9", (lua_Integer) SDL_SCANCODE_KP_9},
    {"KP_0", (lua_Integer) SDL_SCANCODE_KP_0},
    {"KP_PERIOD", (lua_Integer) SDL_SCANCODE_KP_PERIOD},
    {"NONUSBACKSLASH", (lua_Integer) SDL_SCANCODE_NONUSBACKSLASH},
    {"APPLICATION", (lua_Integer) SDL_SCANCODE_APPLICATION},
    {"POWER", (lua_Integer) SDL_SCANCODE_POWER},
    {"KP_EQUALS", (lua_Integer) SDL_SCANCODE_KP_EQUALS},
    {"F13", (lua_Integer) SDL_SCANCODE_F13},
    {"F14", (lua_Integer) SDL_SCANCODE_F14},
    {"F15", (lua_Integer) SDL_SCANCODE_F15},
    {"F16", (lua_Integer) SDL_SCANCODE_F16},
    {"F17", (lua_Integer) SDL_SCANCODE_F17},
    {"F18", (lua_Integer) SDL_SCANCODE_F18},
    {"F19", (lua_Integer) SDL_SCANCODE_F19},
    {"F20", (lua_Integer) SDL_SCANCODE_F20},
    {"F21", (lua_Integer) SDL_SCANCODE_F21},
    {"F22", (lua_Integer) SDL_SCANCODE_F22},
    {"F23", (lua_Integer) SDL_SCANCODE_F23},
    {"F24", (lua_Integer) SDL_SCANCODE_F24},
    {"EXECUTE", (lua_Integer) SDL_SCANCODE_EXECUTE},
    {"HELP", (lua_Integer) SDL_SCANCODE_HELP},
    {"MENU", (lua_Integer) SDL_SCANCODE_MENU},
    {"SELECT", (lua_Integer) SDL_SCANCODE_SELECT},
    {"STOP", (lua_Integer) SDL_SCANCODE_STOP},
    {"AGAIN", (lua_Integer) SDL_SCANCODE_AGAIN},
    {"UNDO", (lua_Integer) SDL_SCANCODE_UNDO},
    {"CUT", (lua_Integer) SDL_SCANCODE_CUT},
    {"COPY", (lua_Integer) SDL_SCANCODE_COPY},
    {"PASTE", (lua_Integer) SDL_SCANCODE_PASTE},
    {"FIND", (lua_Integer) SDL_SCANCODE_FIND},
    {"MUTE", (lua_Integer) SDL_SCANCODE_MUTE},
    {"VOLUMEUP", (lua_Integer) SDL_SCANCODE_VOLUMEUP},
    {"VOLUMEDOWN", (lua_Integer) SDL_SCANCODE_VOLUMEDOWN},
    {"KP_COMMA", (lua_Integer) SDL_SCANCODE_KP_COMMA},
    {"KP_EQUALSAS400", (lua_Integer) SDL_SCANCODE_KP_EQUALSAS400},
    {"INTERNATIONAL1", (lua_Integer) SDL_SCANCODE_INTERNATIONAL1},
    {"INTERNATIONAL2", (lua_Integer) SDL_SCANCODE_INTERNATIONAL2},
    {"INTERNATIONAL3", (lua_Integer) SDL_SCANCODE_INTERNATIONAL3},
    {"INTERNATIONAL4", (lua_Integer) SDL_SCANCODE_INTERNATIONAL4},
    {"INTERNATIONAL5", (lua_Integer) SDL_SCANCODE_INTERNATIONAL5},
    {"INTERNATIONAL6", (lua_Integer) SDL_SCANCODE_INTERNATIONAL6},
    {"INTERNATIONAL7", (lua_Integer) SDL_SCANCODE_INTERNATIONAL7},
    {"INTERNATIONAL8", (lua_Integer) SDL_SCANCODE_INTERNATIONAL8},
    {"INTERNATIONAL9", (lua_Integer) SDL_SCANCODE_INTERNATIONAL9},
    {"LANG1", (lua_Integer) SDL_SCANCODE_LANG1},
    {"LANG2", (lua_Integer) SDL_SCANCODE_LANG2},
    {"LANG3", (lua_Integer) SDL_SCANCODE_LANG3},
    {"LANG4", (lua_Integer) SDL_SCANCODE_LANG4},
    {"LANG5", (lua_Integer) SDL_SCANCODE_LANG5},
    {"LANG6", (lua_Integer) SDL_SCANCODE_LANG6},
    {"LANG7", (lua_Integer) SDL_SCANCODE_LANG7},
    {"LANG8", (lua_Integer) SDL_SCANCODE_LANG8},
    {"LANG9", (lua_Integer) SDL_SCANCODE_LANG9},
    {"ALTERASE", (lua_Integer) SDL_SCANCODE_ALTERASE},
    {"SYSREQ", (lua_Integer) SDL_SCANCODE_SYSREQ},
    {"CANCEL", (lua_Integer) SDL_SCANCODE_CANCEL},
    {"CLEAR", (lua_Integer) SDL_SCANCODE_CLEAR},
    {"PRIOR", (lua_Integer) SDL_SCANCODE_PRIOR},
    {"RETURN2", (lua_Integer) SDL_SCANCODE_RETURN2},
    {"SEPARATOR", (lua_Integer) SDL_SCANCODE_SEPARATOR},
    {"OUT", (lua_Integer) SDL_SCANCODE_OUT},
    {"OPER", (lua_Integer) SDL_SCANCODE_OPER},
    {"CLEARAGAIN", (lua_Integer) SDL_SCANCODE_CLEARAGAIN},
    {"CRSEL", (lua_Integer) SDL_SCANCODE_CRSEL},
    {"EXSEL", (lua_Integer) SDL_SCANCODE_EXSEL},
    {"KP_00", (lua_Integer) SDL_SCANCODE_KP_00},
    {"KP_000", (lua_Integer) SDL_SCANCODE_KP_000},
    {"THOUSANDSSEPARATOR", (lua_Integer) SDL_SCANCODE_THOUSANDSSEPARATOR},
    {"DECIMALSEPARATOR", (lua_Integer) SDL_SCANCODE_DECIMALSEPARATOR},
    {"CURRENCYUNIT", (lua_Integer) SDL_SCANCODE_CURRENCYUNIT},
    {"CURRENCYSUBUNIT", (lua_Integer) SDL_SCANCODE_CURRENCYSUBUNIT},
    {"KP_LEFTPAREN", (lua_Integer) SDL_SCANCODE_KP_LEFTPAREN},
    {"KP_RIGHTPAREN", (lua_Integer) SDL_SCANCODE_KP_RIGHTPAREN},
    {"KP_LEFTBRACE", (lua_Integer) SDL_SCANCODE_KP_LEFTBRACE},
    {"KP_RIGHTBRACE", (lua_Integer) SDL_SCANCODE_KP_RIGHTBRACE},
    {"KP_TAB", (lua_Integer) SDL_SCANCODE_KP_TAB},
    {"KP_BACKSPACE", (lua_Integer) SDL_SCANCODE_KP_BACKSPACE},
    {"KP_A", (lua_Integer) SDL_SCANCODE_KP_A},
    {"KP_B", (lua_Integer) SDL_SCANCODE_KP_B},
    {"KP_C", (lua_Integer) SDL_SCANCODE_KP_C},
    {"KP_D", (lua_Integer) SDL_SCANCODE_KP_D},
    {"KP_E", (lua_Integer) SDL_SCANCODE_KP_E},
    {"KP_F", (lua_Integer) SDL_SCANCODE_KP_F},
    {"KP_XOR", (lua_Integer) SDL_SCANCODE_KP_XOR},
    {"KP_POWER", (lua_Integer) SDL_SCANCODE_KP_POWER},
    {"KP_PERCENT", (lua_Integer) SDL_SCANCODE_KP_PERCENT},
    {"KP_LESS", (lua_Integer) SDL_SCANCODE_KP_LESS},
    {"KP_GREATER", (lua_Integer) SDL_SCANCODE_KP_GREATER},
    {"KP_AMPERSAND", (lua_Integer) SDL_SCANCODE_KP_AMPERSAND},
    {"KP_DBLAMPERSAND", (lua_Integer) SDL_SCANCODE_KP_DBLAMPERSAND},
    {"KP_VERTICALBAR", (lua_Integer) SDL_SCANCODE_KP_VERTICALBAR},
    {"KP_DBLVERTICALBAR", (lua_Integer) SDL_SCANCODE_KP_DBLVERTICALBAR},
    {"KP_COLON", (lua_Integer) SDL_SCANCODE_KP_COLON},
    {"KP_HASH", (lua_Integer) SDL_SCANCODE_KP_HASH},
    {"KP_SPACE", (lua_Integer) SDL_SCANCODE_KP_SPACE},
    {"KP_AT", (lua_Integer) SDL_SCANCODE_KP_AT},
    {"KP_EXCLAM", (lua_Integer) SDL_SCANCODE_KP_EXCLAM},
    {"KP_MEMSTORE", (lua_Integer) SDL_SCANCODE_KP_MEMSTORE},
    {"KP_MEMRECALL", (lua_Integer) SDL_SCANCODE_KP_MEMRECALL},
    {"KP_MEMCLEAR", (lua_Integer) SDL_SCANCODE_KP_MEMCLEAR},
    {"KP_MEMADD", (lua_Integer) SDL_SCANCODE_KP_MEMADD},
    {"KP_MEMSUBTRACT", (lua_Integer) SDL_SCANCODE_KP_MEMSUBTRACT},
    {"KP_MEMMULTIPLY", (lua_Integer) SDL_SCANCODE_KP_MEMMULTIPLY},
    {"KP_MEMDIVIDE", (lua_Integer) SDL_SCANCODE_KP_MEMDIVIDE},
    {"KP_PLUSMINUS", (lua_Integer) SDL_SCANCODE_KP_PLUSMINUS},
    {"KP_CLEAR", (lua_Integer) SDL_SCANCODE_KP_CLEAR},
    {"KP_CLEARENTRY", (lua_Integer) SDL_SCANCODE_KP_CLEARENTRY},
    {"KP_BINARY", (lua_Integer) SDL_SCANCODE_KP_BINARY},
    {"KP_OCTAL", (lua_Integer) SDL_SCANCODE_KP_OCTAL},
    {"KP_DECIMAL", (lua_Integer) SDL_SCANCODE_KP_DECIMAL},
    {"KP_HEXADECIMAL", (lua_Integer) SDL_SCANCODE_KP_HEXADECIMAL},
    {"LCTRL", (lua_Integer) SDL_SCANCODE_LCTRL},
    {"LSHIFT", (lua_Integer) SDL_SCANCODE_LSHIFT},
    {"LALT", (lua_Integer) SDL_SCANCODE_LALT},
    {"LGUI", (lua_Integer) SDL_SCANCODE_LGUI},
    {"RCTRL", (lua_Integer) SDL_SCANCODE_RCTRL},
    {"RSHIFT", (lua_Integer) SDL_SCANCODE_RSHIFT},
    {"RALT", (lua_Integer) SDL_SCANCODE_RALT},
    {"RGUI", (lua_Integer) SDL_SCANCODE_RGUI},
    {"MODE", (lua_Integer) SDL_SCANCODE_MODE},
    {"AUDIONEXT", (lua_Integer) SDL_SCANCODE_AUDIONEXT},
    {"AUDIOPREV", (lua_Integer) SDL_SCANCODE_AUDIOPREV},
    {"AUDIOSTOP", (lua_Integer) SDL_SCANCODE_AUDIOSTOP},
    {"AUDIOPLAY", (lua_Integer) SDL_SCANCODE_AUDIOPLAY},
    {"AUDIOMUTE", (lua_Integer) SDL_SCANCODE_AUDIOMUTE},
    {"MEDIASELECT", (lua_Integer) SDL_SCANCODE_MEDIASELECT},
    {"WWW", (lua_Integer) SDL_SCANCODE_WWW},
    {"MAIL", (lua_Integer) SDL_SCANCODE_MAIL},
    {"CALCULATOR", (lua_Integer) SDL_SCANCODE_CALCULATOR},
    {"COMPUTER", (lua_Integer) SDL_SCANCODE_COMPUTER},
    {"AC_SEARCH", (lua_Integer) SDL_SCANCODE_AC_SEARCH},
    {"AC_HOME", (lua_Integer) SDL_SCANCODE_AC_HOME},
    {"AC_BACK", (lua_Integer) SDL_SCANCODE_AC_BACK},
    {"AC_FORWARD", (lua_Integer) SDL_SCANCODE_AC_FORWARD},
    {"AC_STOP", (lua_Integer) SDL_SCANCODE_AC_STOP},
    {"AC_REFRESH", (lua_Integer) SDL_SCANCODE_AC_REFRESH},
    {"AC_BOOKMARKS", (lua_Integer) SDL_SCANCODE_AC_BOOKMARKS},
    {"BRIGHTNESSDOWN", (lua_Integer) SDL_SCANCODE_BRIGHTNESSDOWN},
    {"BRIGHTNESSUP", (lua_Integer) SDL_SCANCODE_BRIGHTNESSUP},
    {"DISPLAYSWITCH", (lua_Integer) SDL_SCANCODE_DISPLAYSWITCH},
    {"KBDILLUMTOGGLE", (lua_Integer) SDL_SCANCODE_KBDILLUMTOGGLE},
    {"KBDILLUMDOWN", (lua_Integer) SDL_SCANCODE_KBDILLUMDOWN},
    {"KBDILLUMUP", (lua_Integer) SDL_SCANCODE_KBDILLUMUP},
    {"EJECT", (lua_Integer) SDL_SCANCODE_EJECT},
    {"SLEEP", (lua_Integer) SDL_SCANCODE_SLEEP},
    {"APP1", (lua_Integer) SDL_SCANCODE_APP1},
    {"APP2", (lua_Integer) SDL_SCANCODE_APP2},
    {"AUDIOREWIND", (lua_Integer) SDL_SCANCODE_AUDIOREWIND},
    {"AUDIOFASTFORWARD", (lua_Integer) SDL_SCANCODE_AUDIOFASTFORWARD},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_keycode_enum_xl[] = {
    {"UNKNOWN", (lua_Integer) SDLK_UNKNOWN},
    {"RETURN", (lua_Integer) SDLK_RETURN},
    {"ESCAPE", (lua_Integer) SDLK_ESCAPE},
    {"BACKSPACE", (lua_Integer) SDLK_BACKSPACE},
    {"TAB", (lua_Integer) SDLK_TAB},
    {"SPACE", (lua_Integer) SDLK_SPACE},
    {"EXCLAIM", (lua_Integer) SDLK_EXCLAIM},
    {"QUOTEDBL", (lua_Integer) SDLK_QUOTEDBL},
    {"HASH", (lua_Integer) SDLK_HASH},
    {"PERCENT", (lua_Integer) SDLK_PERCENT},
    {"DOLLAR", (lua_Integer) SDLK_DOLLAR},
    {"AMPERSAND", (lua_Integer) SDLK_AMPERSAND},
    {"QUOTE", (lua_Integer) SDLK_QUOTE},
    {"LEFTPAREN", (lua_Integer) SDLK_LEFTPAREN},
    {"RIGHTPAREN", (lua_Integer) SDLK_RIGHTPAREN},
    {"ASTERISK", (lua_Integer) SDLK_ASTERISK},
    {"PLUS", (lua_Integer) SDLK_PLUS},
    {"COMMA", (lua_Integer) SDLK_COMMA},
    {"MINUS", (lua_Integer) SDLK_MINUS},
    {"PERIOD", (lua_Integer) SDLK_PERIOD},
    {"SLASH", (lua_Integer) SDLK_SLASH},
    {"0", (lua_Integer) SDLK_0},
    {"1", (lua_Integer) SDLK_1},
    {"2", (lua_Integer) SDLK_2},
    {"3", (lua_Integer) SDLK_3},
    {"4", (lua_Integer) SDLK_4},
    {"5", (lua_Integer) SDLK_5},
    {"6", (lua_Integer) SDLK_6},
    {"7", (lua_Integer) SDLK_7},
    {"8", (lua_Integer) SDLK_8},
    {"9", (lua_Integer) SDLK_9},
    {"COLON", (lua_Integer) SDLK_COLON},
    {"SEMICOLON", (lua_Integer) SDLK_SEMICOLON},
    {"LESS", (lua_Integer) SDLK_LESS},
    {"EQUALS", (lua_Integer) SDLK_EQUALS},
    {"GREATER", (lua_Integer) SDLK_GREATER},
    {"QUESTION", (lua_Integer) SDLK_QUESTION},
    {"AT", (lua_Integer) SDLK_AT},
    {"LEFTBRACKET", (lua_Integer) SDLK_LEFTBRACKET},
    {"BACKSLASH", (lua_Integer) SDLK_BACKSLASH},
    {"RIGHTBRACKET", (lua_Integer) SDLK_RIGHTBRACKET},
    {"CARET", (lua_Integer) SDLK_CARET},
    {"UNDERSCORE", (lua_Integer) SDLK_UNDERSCORE},
    {"BACKQUOTE", (lua_Integer) SDLK_BACKQUOTE},
    {"a", (lua_Integer) SDLK_a},
    {"b", (lua_Integer) SDLK_b},
    {"c", (lua_Integer) SDLK_c},
    {"d", (lua_Integer) SDLK_d},
    {"e", (lua_Integer) SDLK_e},
    {"f", (lua_Integer) SDLK_f},
    {"g", (lua_Integer) SDLK_g},
    {"h", (lua_Integer) SDLK_h},
    {"i", (lua_Integer) SDLK_i},
    {"j", (lua_Integer) SDLK_j},
    {"k", (lua_Integer) SDLK_k},
    {"l", (lua_Integer) SDLK_l},
    {"m", (lua_Integer) SDLK_m},
    {"n", (lua_Integer) SDLK_n},
    {"o", (lua_Integer) SDLK_o},
    {"p", (lua_Integer) SDLK_p},
    {"q", (lua_Integer) SDLK_q},
    {"r", (lua_Integer) SDLK_r},
    {"s", (lua_Integer) SDLK_s},
    {"t", (lua_Integer) SDLK_t},
    {"u", (lua_Integer) SDLK_u},
    {"v", (lua_Integer) SDLK_v},
    {"w", (lua_Integer) SDLK_w},
    {"x", (lua_Integer) SDLK_x},
    {"y", (lua_Integer) SDLK_y},
    {"z", (lua_Integer) SDLK_z},
    {"CAPSLOCK", (lua_Integer) SDLK_CAPSLOCK},
    {"F1", (lua_Integer) SDLK_F1},
    {"F2", (lua_Integer) SDLK_F2},
    {"F3", (lua_Integer) SDLK_F3},
    {"F4", (lua_Integer) SDLK_F4},
    {"F5", (lua_Integer) SDLK_F5},
    {"F6", (lua_Integer) SDLK_F6},
    {"F7", (lua_Integer) SDLK_F7},
    {"F8", (lua_Integer) SDLK_F8},
    {"F9", (lua_Integer) SDLK_F9},
    {"F10", (lua_Integer) SDLK_F10},
    {"F11", (lua_Integer) SDLK_F11},
    {"F12", (lua_Integer) SDLK_F12},
    {"PRINTSCREEN", (lua_Integer) SDLK_PRINTSCREEN},
    {"SCROLLLOCK", (lua_Integer) SDLK_SCROLLLOCK},
    {"PAUSE", (lua_Integer) SDLK_PAUSE},
    {"INSERT", (lua_Integer) SDLK_INSERT},
    {"HOME", (lua_Integer) SDLK_HOME},
    {"PAGEUP", (lua_Integer) SDLK_PAGEUP},
    {"DELETE", (lua_Integer) SDLK_DELETE},
    {"END", (lua_Integer) SDLK_END},
    {"PAGEDOWN", (lua_Integer) SDLK_PAGEDOWN},
    {"RIGHT", (lua_Integer) SDLK_RIGHT},
    {"LEFT", (lua_Integer) SDLK_LEFT},
    {"DOWN", (lua_Integer) SDLK_DOWN},
    {"UP", (lua_Integer) SDLK_UP},
    {"NUMLOCKCLEAR", (lua_Integer) SDLK_NUMLOCKCLEAR},
    {"KP_DIVIDE", (lua_Integer) SDLK_KP_DIVIDE},
    {"KP_MULTIPLY", (lua_Integer) SDLK_KP_MULTIPLY},
    {"KP_MINUS", (lua_Integer) SDLK_KP_MINUS},
    {"KP_PLUS", (lua_Integer) SDLK_KP_PLUS},
    {"KP_ENTER", (lua_Integer) SDLK_KP_ENTER},
    {"KP_1", (lua_Integer) SDLK_KP_1},
    {"KP_2", (lua_Integer) SDLK_KP_2},
    {"KP_3", (lua_Integer) SDLK_KP_3},
    {"KP_4", (lua_Integer) SDLK_KP_4},
    {"KP_5", (lua_Integer) SDLK_KP_5},
    {"KP_6", (lua_Integer) SDLK_KP_6},
    {"KP_7", (lua_Integer) SDLK_KP_7},
    {"KP_8", (lua_Integer) SDLK_KP_8},
    {"KP_9", (lua_Integer) SDLK_KP_9},
    {"KP_0", (lua_Integer) SDLK_KP_0},
    {"KP_PERIOD", (lua_Integer) SDLK_KP_PERIOD},
    {"APPLICATION", (lua_Integer) SDLK_APPLICATION},
    {"POWER", (lua_Integer) SDLK_POWER},
    {"KP_EQUALS", (lua_Integer) SDLK_KP_EQUALS},
    {"F13", (lua_Integer) SDLK_F13},
    {"F14", (lua_Integer) SDLK_F14},
    {"F15", (lua_Integer) SDLK_F15},
    {"F16", (lua_Integer) SDLK_F16},
    {"F17", (lua_Integer) SDLK_F17},
    {"F18", (lua_Integer) SDLK_F18},
    {"F19", (lua_Integer) SDLK_F19},
    {"F20", (lua_Integer) SDLK_F20},
    {"F21", (lua_Integer) SDLK_F21},
    {"F22", (lua_Integer) SDLK_F22},
    {"F23", (lua_Integer) SDLK_F23},
    {"F24", (lua_Integer) SDLK_F24},
    {"EXECUTE", (lua_Integer) SDLK_EXECUTE},
    {"HELP", (lua_Integer) SDLK_HELP},
    {"MENU", (lua_Integer) SDLK_MENU},
    {"SELECT", (lua_Integer) SDLK_SELECT},
    {"STOP", (lua_Integer) SDLK_STOP},
    {"AGAIN", (lua_Integer) SDLK_AGAIN},
    {"UNDO", (lua_Integer) SDLK_UNDO},
    {"CUT", (lua_Integer) SDLK_CUT},
    {"COPY", (lua_Integer) SDLK_COPY},
    {"PASTE", (lua_Integer) SDLK_PASTE},
    {"FIND", (lua_Integer) SDLK_FIND},
    {"MUTE", (lua_Integer) SDLK_MUTE},
    {"VOLUMEUP", (lua_Integer) SDLK_VOLUMEUP},
    {"VOLUMEDOWN", (lua_Integer) SDLK_VOLUMEDOWN},
    {"KP_COMMA", (lua_Integer) SDLK_KP_COMMA},
    {"KP_EQUALSAS400", (lua_Integer) SDLK_KP_EQUALSAS400},
    {"ALTERASE", (lua_Integer) SDLK_ALTERASE},
    {"SYSREQ", (lua_Integer) SDLK_SYSREQ},
    {"CANCEL", (lua_Integer) SDLK_CANCEL},
    {"CLEAR", (lua_Integer) SDLK_CLEAR},
    {"PRIOR", (lua_Integer) SDLK_PRIOR},
    {"RETURN2", (lua_Integer) SDLK_RETURN2},
    {"SEPARATOR", (lua_Integer) SDLK_SEPARATOR},
    {"OUT", (lua_Integer) SDLK_OUT},
    {"OPER", (lua_Integer) SDLK_OPER},
    {"CLEARAGAIN", (lua_Integer) SDLK_CLEARAGAIN},
    {"CRSEL", (lua_Integer) SDLK_CRSEL},
    {"EXSEL", (lua_Integer) SDLK_EXSEL},
    {"KP_00", (lua_Integer) SDLK_KP_00},
    {"KP_000", (lua_Integer) SDLK_KP_000},
    {"THOUSANDSSEPARATOR", (lua_Integer) SDLK_THOUSANDSSEPARATOR},
    {"DECIMALSEPARATOR", (lua_Integer) SDLK_DECIMALSEPARATOR},
    {"CURRENCYUNIT", (lua_Integer) SDLK_CURRENCYUNIT},
    {"CURRENCYSUBUNIT", (lua_Integer) SDLK_CURRENCYSUBUNIT},
    {"KP_LEFTPAREN", (lua_Integer) SDLK_KP_LEFTPAREN},
    {"KP_RIGHTPAREN", (lua_Integer) SDLK_KP_RIGHTPAREN},
    {"KP_LEFTBRACE", (lua_Integer) SDLK_KP_LEFTBRACE},
    {"KP_RIGHTBRACE", (lua_Integer) SDLK_KP_RIGHTBRACE},
    {"KP_TAB", (lua_Integer) SDLK_KP_TAB},
    {"KP_BACKSPACE", (lua_Integer) SDLK_KP_BACKSPACE},
    {"KP_A", (lua_Integer) SDLK_KP_A},
    {"KP_B", (lua_Integer) SDLK_KP_B},
    {"KP_C", (lua_Integer) SDLK_KP_C},
    {"KP_D", (lua_Integer) SDLK_KP_D},
    {"KP_E", (lua_Integer) SDLK_KP_E},
    {"KP_F", (lua_Integer) SDLK_KP_F},
    {"KP_XOR", (lua_Integer) SDLK_KP_XOR},
    {"KP_POWER", (lua_Integer) SDLK_KP_POWER},
    {"KP_PERCENT", (lua_Integer) SDLK_KP_PERCENT},
    {"KP_LESS", (lua_Integer) SDLK_KP_LESS},
    {"KP_GREATER", (lua_Integer) SDLK_KP_GREATER},
    {"KP_AMPERSAND", (lua_Integer) SDLK_KP_AMPERSAND},
    {"KP_DBLAMPERSAND", (lua_Integer) SDLK_KP_DBLAMPERSAND},
    {"KP_VERTICALBAR", (lua_Integer) SDLK_KP_VERTICALBAR},
    {"KP_DBLVERTICALBAR", (lua_Integer) SDLK_KP_DBLVERTICALBAR},
    {"KP_COLON", (lua_Integer) SDLK_KP_COLON},
    {"KP_HASH", (lua_Integer) SDLK_KP_HASH},
    {"KP_SPACE", (lua_Integer) SDLK_KP_SPACE},
    {"KP_AT", (lua_Integer) SDLK_KP_AT},
    {"KP_EXCLAM", (lua_Integer) SDLK_KP_EXCLAM},
    {"KP_MEMSTORE", (lua_Integer) SDLK_KP_MEMSTORE},
    {"KP_MEMRECALL", (lua_Integer) SDLK_KP_MEMRECALL},
    {"KP_MEMCLEAR", (lua_Integer) SDLK_KP_MEMCLEAR},
    {"KP_MEMADD", (lua_Integer) SDLK_KP_MEMADD},
    {"KP_MEMSUBTRACT", (lua_Integer) SDLK_KP_MEMSUBTRACT},
    {"KP_MEMMULTIPLY", (lua_Integer) SDLK_KP_MEMMULTIPLY},
    {"KP_MEMDIVIDE", (lua_Integer) SDLK_KP_MEMDIVIDE},
    {"KP_PLUSMINUS", (lua_Integer) SDLK_KP_PLUSMINUS},
    {"KP_CLEAR", (lua_Integer) SDLK_KP_CLEAR},
    {"KP_CLEARENTRY", (lua_Integer) SDLK_KP_CLEARENTRY},
    {"KP_BINARY", (lua_Integer) SDLK_KP_BINARY},
    {"KP_OCTAL", (lua_Integer) SDLK_KP_OCTAL},
    {"KP_DECIMAL", (lua_Integer) SDLK_KP_DECIMAL},
    {"KP_HEXADECIMAL", (lua_Integer) SDLK_KP_HEXADECIMAL},
    {"LCTRL", (lua_Integer) SDLK_LCTRL},
    {"LSHIFT", (lua_Integer) SDLK_LSHIFT},
    {"LALT", (lua_Integer) SDLK_LALT},
    {"LGUI", (lua_Integer) SDLK_LGUI},
    {"RCTRL", (lua_Integer) SDLK_RCTRL},
    {"RSHIFT", (lua_Integer) SDLK_RSHIFT},
    {"RALT", (lua_Integer) SDLK_RALT},
    {"RGUI", (lua_Integer) SDLK_RGUI},
    {"MODE", (lua_Integer) SDLK_MODE},
    {"AUDIONEXT", (lua_Integer) SDLK_AUDIONEXT},
    {"AUDIOPREV", (lua_Integer) SDLK_AUDIOPREV},
    {"AUDIOSTOP", (lua_Integer) SDLK_AUDIOSTOP},
    {"AUDIOPLAY", (lua_Integer) SDLK_AUDIOPLAY},
    {"AUDIOMUTE", (lua_Integer) SDLK_AUDIOMUTE},
    {"MEDIASELECT", (lua_Integer) SDLK_MEDIASELECT},
    {"WWW", (lua_Integer) SDLK_WWW},
    {"MAIL", (lua_Integer) SDLK_MAIL},
    {"CALCULATOR", (lua_Integer) SDLK_CALCULATOR},
    {"COMPUTER", (lua_Integer) SDLK_COMPUTER},
    {"AC_SEARCH", (lua_Integer) SDLK_AC_SEARCH},
    {"AC_HOME", (lua_Integer) SDLK_AC_HOME},
    {"AC_BACK", (lua_Integer) SDLK_AC_BACK},
    {"AC_FORWARD", (lua_Integer) SDLK_AC_FORWARD},
    {"AC_STOP", (lua_Integer) SDLK_AC_STOP},
    {"AC_REFRESH", (lua_Integer) SDLK_AC_REFRESH},
    {"AC_BOOKMARKS", (lua_Integer) SDLK_AC_BOOKMARKS},
    {"BRIGHTNESSDOWN", (lua_Integer) SDLK_BRIGHTNESSDOWN},
    {"BRIGHTNESSUP", (lua_Integer) SDLK_BRIGHTNESSUP},
    {"DISPLAYSWITCH", (lua_Integer) SDLK_DISPLAYSWITCH},
    {"KBDILLUMTOGGLE", (lua_Integer) SDLK_KBDILLUMTOGGLE},
    {"KBDILLUMDOWN", (lua_Integer) SDLK_KBDILLUMDOWN},
    {"KBDILLUMUP", (lua_Integer) SDLK_KBDILLUMUP},
    {"EJECT", (lua_Integer) SDLK_EJECT},
    {"SLEEP", (lua_Integer) SDLK_SLEEP},
    {"APP1", (lua_Integer) SDLK_APP1},
    {"APP2", (lua_Integer) SDLK_APP2},
    {"AUDIOREWIND", (lua_Integer) SDLK_AUDIOREWIND},
    {"AUDIOFASTFORWARD", (lua_Integer) SDLK_AUDIOFASTFORWARD},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_keymod_enum_xl[] = {
    {"NONE", (lua_Integer) KMOD_NONE},
    {"LSHIFT", (lua_Integer) KMOD_LSHIFT},
    {"RSHIFT", (lua_Integer) KMOD_RSHIFT},
    {"LCTRL", (lua_Integer) KMOD_LCTRL},
    {"RCTRL", (lua_Integer) KMOD_RCTRL},
    {"LALT", (lua_Integer) KMOD_LALT},
    {"RALT", (lua_Integer) KMOD_RALT},
    {"LGUI", (lua_Integer) KMOD_LGUI},
    {"RGUI", (lua_Integer) KMOD_RGUI},
    {"NUM", (lua_Integer) KMOD_NUM},
    {"CAPS", (lua_Integer) KMOD_CAPS},
    {"MODE", (lua_Integer) KMOD_MODE},
    {"RESERVED", (lua_Integer) KMOD_RESERVED},
    {"CTRL", (lua_Integer) KMOD_CTRL},
    {"SHIFT", (lua_Integer) KMOD_SHIFT},
    {"ALT", (lua_Integer) KMOD_ALT},
    {"GUI", (lua_Integer) KMOD_GUI},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_button_enum_xl[] = {
    {"LEFT", (lua_Integer) SDL_BUTTON_LEFT},
    {"MIDDLE", (lua_Integer) SDL_BUTTON_MIDDLE},
    {"RIGHT", (lua_Integer) SDL_BUTTON_RIGHT},
    {"X1", (lua_Integer) SDL_BUTTON_X1},
    {"X2", (lua_Integer) SDL_BUTTON_X2},
    {"LMASK", (lua_Integer) SDL_BUTTON_LMASK},
    {"MMASK", (lua_Integer) SDL_BUTTON_MMASK},
    {"RMASK", (lua_Integer) SDL_BUTTON_RMASK},
    {"X1MASK", (lua_Integer) SDL_BUTTON_X1MASK},
    {"X2MASK", (lua_Integer) SDL_BUTTON_X2MASK},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_touch_enum_xl[] = {
    {"MOUSEID", (lua_Integer) SDL_TOUCH_MOUSEID},
    {NULL, (lua_Integer) 0},
};

static XL_EnumEntry sdl_systemcursor_enum_xl[] = {
    {"ARROW", (lua_Integer) SDL_SYSTEM_CURSOR_ARROW},
    {"IBEAM", (lua_Integer) SDL_SYSTEM_CURSOR_IBEAM},
    {"WAIT", (lua_Integer) SDL_SYSTEM_CURSOR_WAIT},
    {"CROSSHAIR", (lua_Integer) SDL_SYSTEM_CURSOR_CROSSHAIR},
    {"WAITARROW", (lua_Integer) SDL_SYSTEM_CURSOR_WAITARROW},
    {"SIZENWSE", (lua_Integer) SDL_SYSTEM_CURSOR_SIZENWSE},
    {"SIZENESW", (lua_Integer) SDL_SYSTEM_CURSOR_SIZENESW},
    {"SIZEWE", (lua_Integer) SDL_SYSTEM_CURSOR_SIZEWE},
    {"SIZENS", (lua_Integer) SDL_SYSTEM_CURSOR_SIZENS},
    {"SIZEALL", (lua_Integer) SDL_SYSTEM_CURSOR_SIZEALL},
    {"NO", (lua_Integer) SDL_SYSTEM_CURSOR_NO},
    {"HAND", (lua_Integer) SDL_SYSTEM_CURSOR_HAND},
    {NULL, (lua_Integer) 0},
};

int R_lua_sdl_init(lua_State *L)
{
    XL_initmetatable(L, "SDL_Event", sdl_event_method_registry_xl);
    XL_initmetatable(L, "SDL_KeyboardEvent", sdl_keyboardevent_method_registry_xl);
    XL_initmetatable(L, "SDL_MouseButtonEvent", sdl_mousebuttonevent_method_registry_xl);
    XL_initmetatable(L, "SDL_MouseMotionEvent", sdl_mousemotionevent_method_registry_xl);
    XL_initmetatable(L, "SDL_WindowEvent", sdl_windowevent_method_registry_xl);
    XL_initindextable(L, &sdl_event_index_dummy_xl, sdl_event_index_registry_xl);
    XL_initindextable(L, &sdl_keyboardevent_index_dummy_xl, sdl_keyboardevent_index_registry_xl);
    XL_initindextable(L, &sdl_mousebuttonevent_index_dummy_xl, sdl_mousebuttonevent_index_registry_xl);
    XL_initindextable(L, &sdl_mousemotionevent_index_dummy_xl, sdl_mousemotionevent_index_registry_xl);
    XL_initindextable(L, &sdl_windowevent_index_dummy_xl, sdl_windowevent_index_registry_xl);
    XL_initindextable(L, &sdl_staticindex_dummy_xl, sdl_staticindex_registry_xl);
    XL_initnewindextable(L, &sdl_staticnewindex_dummy_xl, sdl_staticnewindex_registry_xl);
    XL_initstaticmetatable(L, "SDL", (const char *)NULL);
    XL_initfunctions(L, sdl_function_registry_xl, "SDL", (const char *)NULL);
    XL_initenum(L, sdl_window_enum_xl, "SDL", "Window", (const char *)NULL);
    XL_initenum(L, sdl_eventtype_enum_xl, "SDL", "EventType", (const char *)NULL);
    XL_initenum(L, sdl_windoweventtype_enum_xl, "SDL", "WindowEventType", (const char *)NULL);
    XL_initenum(L, sdl_keyboardevent_state_enum_xl, "SDL", "KeyboardEvent", "State", (const char *)NULL);
    XL_initenum(L, sdl_scancode_enum_xl, "SDL", "Scancode", (const char *)NULL);
    XL_initenum(L, sdl_keycode_enum_xl, "SDL", "Keycode", (const char *)NULL);
    XL_initenum(L, sdl_keymod_enum_xl, "SDL", "Keymod", (const char *)NULL);
    XL_initenum(L, sdl_button_enum_xl, "SDL", "Button", (const char *)NULL);
    XL_initenum(L, sdl_touch_enum_xl, "SDL", "Touch", (const char *)NULL);
    XL_initenum(L, sdl_systemcursor_enum_xl, "SDL", "SystemCursor", (const char *)NULL);
    return 0;
}
