/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_v2_new_xl(lua_State *L)
{
    float x = XL_checkfloat(L, 1);
    float y = XL_checkfloat(L, 2);
    R_V2 RETVAL;
    RETVAL = R_v2(x, y);
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_v2_x_index_xl(lua_State *L)
{
    R_V2 *self = XL_checkutype(L, 1, "R_V2");
    float RETVAL;
    RETVAL = self->x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_v2_x_newindex_xl(lua_State *L)
{
    R_V2 *self = XL_checkutype(L, 1, "R_V2");
    float VALUE = XL_checkfloat(L, 2);
    self->x = VALUE;
    return 0;
}

static int r_v2_y_index_xl(lua_State *L)
{
    R_V2 *self = XL_checkutype(L, 1, "R_V2");
    float RETVAL;
    RETVAL = self->y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_v2_y_newindex_xl(lua_State *L)
{
    R_V2 *self = XL_checkutype(L, 1, "R_V2");
    float VALUE = XL_checkfloat(L, 2);
    self->y = VALUE;
    return 0;
}

static int r_v2_method_tostring_xl(lua_State *L)
{
    R_V2 *self = XL_checkutype(L, 1, "R_V2");
    lua_pushfstring(L, "R_V2(%f, %f)", R_lua_float2n(self->x),
                                       R_lua_float2n(self->y));
    return 1;
}

static int r_v2_method_unpack_xl(lua_State *L)
{
    R_V2 *self = XL_checkutype(L, 1, "R_V2");
    XL_pushfloat(L, self->x);
    XL_pushfloat(L, self->y);
    return 2;
}

static int r_v2_method_set_xl(lua_State *L)
{
    return XL_setfromtable(L, "R_V2", 1, 2);
}

static int r_affinetransform_origin_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 RETVAL;
    RETVAL = self->origin;
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_affinetransform_origin_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->origin = VALUE;
    return 0;
}

static int r_affinetransform_origin_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->origin.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_origin_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->origin.x = VALUE;
    return 0;
}

static int r_affinetransform_origin_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->origin.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_origin_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->origin.x = VALUE;
    return 0;
}

static int r_affinetransform_pos_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 RETVAL;
    RETVAL = self->pos;
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_affinetransform_pos_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->pos = VALUE;
    return 0;
}

static int r_affinetransform_pos_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->pos.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_pos_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->pos.x = VALUE;
    return 0;
}

static int r_affinetransform_pos_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->pos.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_pos_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->pos.y = VALUE;
    return 0;
}

static int r_affinetransform_scale_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 RETVAL;
    RETVAL = self->scale;
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_affinetransform_scale_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->scale = VALUE;
    return 0;
}

static int r_affinetransform_scale_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->scale.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_scale_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->scale.x = VALUE;
    return 0;
}

static int r_affinetransform_scale_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->scale.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_scale_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->scale.y = VALUE;
    return 0;
}

static int r_affinetransform_skew_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 RETVAL;
    RETVAL = self->skew;
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_affinetransform_skew_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->skew = VALUE;
    return 0;
}

static int r_affinetransform_skew_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->skew.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_skew_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->skew.x = VALUE;
    return 0;
}

static int r_affinetransform_skew_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->skew.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_skew_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->skew.y = VALUE;
    return 0;
}

static int r_affinetransform_angle_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->angle;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_angle_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->angle = VALUE;
    return 0;
}

static int r_affinetransform_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->pos.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->pos.x = VALUE;
    return 0;
}

static int r_affinetransform_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float RETVAL;
    RETVAL = self->pos.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = XL_checkutype(L, 1, "R_AffineTransform");
    float VALUE = XL_checkfloat(L, 2);
    self->pos.y = VALUE;
    return 0;
}

static int r_affinetransform_method_set_xl(lua_State *L)
{
    return XL_setfromtable(L, "R_AffineTransform", 1, 2);
}

static int r_sprite_new_xl(lua_State *L)
{
    const char *name = luaL_checkstring(L, 1);
    R_Sprite *RETVAL;
    int argc = lua_gettop(L);
    RETVAL   = R_sprite_new(name);
    XL_pushnewpptype(L, RETVAL, "R_Sprite");
    if (argc >= 2) {
        lua_getfield(L, -1, "set");
        lua_pushvalue(L, -2);
        lua_pushvalue(L, 2);
        lua_call(L, 2, 0);
    }
    return 1;
}

static int r_sprite_method_gc_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype_nullable(L, 1, "R_Sprite");
    R_sprite_decref(self);
    return 0;
}

static int r_sprite_name_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    const char *RETVAL;
    RETVAL = R_sprite_name(self);
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_sprite_name_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    luaL_checkany(L, 2);
    int VALUE = 2;
    if (lua_isnil(L, VALUE)) {
        R_sprite_name_set(self, NULL);
    }
    else {
        const char *name = luaL_checkstring(L, VALUE);
        R_sprite_name_set(self, name);
    }
    return 0;
}


static void free_user(R_UserData user)
{
    R_lua_value_free(user.data);
}


static int r_sprite_user_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_LuaValue *lv = R_sprite_user(self).data;
    if (lv) {
        R_lua_getreg(L, lv->reg);
    }
    else {
        lua_pushnil(L);
    }
    return 1;
}

static int r_sprite_user_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    luaL_checkany(L, 2);
    int VALUE = 2;
    R_LuaValue *lv = R_sprite_user(self).data;
    bool have_value = !lua_isnil(L, VALUE);
    if (lv) {
        if (have_value) {
            lua_pushvalue(L, VALUE);
            R_lua_unreg(L, lv->reg);
            lv->reg = R_lua_reg(L);
        }
        else {
            R_lua_value_free(lv);
            R_sprite_user_set(self, R_user_null(), NULL);
        }
    }
    else if (have_value) {
        lv = R_lua_value_new(L, VALUE);
        R_sprite_user_set(self, R_user_data(lv), free_user);
    }
    return 0;
}

static int r_sprite_parent_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_Sprite *RETVAL;
    RETVAL = R_sprite_parent(self);
    if (RETVAL) {
        R_sprite_incref(RETVAL);
    }
    XL_pushnewpptype_nullable(L, RETVAL, "R_Sprite");
    return 1;
}


static void draw_lua_value(R_Nvg *nvg, const float matrix[static 6],
                           R_UserData user)
{
    R_LUA_VALUE_DECLARE_UNPACK(user.data, lv, L);
    R_lua_getreg(L, lv->reg);
    XL_pushnewpptype(L, nvg, "R_Nvg");
    R_nvg_incref(nvg);
    XL_pushnewutype(L, matrix, sizeof(R_LuaNvgTransform), "R_LuaNvgTransform");
    if (lua_pcall(L, 2, 0, 0)) {
        R_LUA_ERROR_TO_WARNING(L);
    }
}

static void free_lua_value(R_UserData user)
{
    R_lua_value_free(user.data);
}



static int r_sprite_content_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    luaL_checkany(L, 2);
    int VALUE = 2;
    void **pp;
    if ((pp = luaL_testudata(L, VALUE, "R_VectorImage"))) {
        R_VectorImage *field = *pp;
        R_sprite_draw_vector_image(self, field);
    }
    else if ((pp = luaL_testudata(L, VALUE, "R_BitmapImage"))) {
        R_BitmapImage *field = *pp;
        R_sprite_draw_bitmap_image(self, field);
    }
    else if ((pp = luaL_testudata(L, VALUE, "R_TextField"))) {
        R_TextField *field = *pp;
        R_sprite_draw_text_field(self, field);
    }
    else if (lua_isfunction(L, VALUE)) {
        R_LuaValue *lv = R_lua_value_new(L, VALUE);
        R_sprite_draw_fn(self, draw_lua_value, free_lua_value, R_user_data(lv));
    }
    else if (lua_isnil(L, VALUE)) {
        R_sprite_draw_null(self);
    }
    else {
        luaL_error(L, "Don't know how to draw a value of type %s",
                      luaL_typename(L, VALUE));
    }
    return 0;
}

static int r_sprite_method_set_xl(lua_State *L)
{
    return XL_setfromtable(L, "R_Sprite", 1, 2);
}

static int r_sprite_transform_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_AffineTransform RETVAL;
    RETVAL = R_sprite_transform(self);
    XL_pushnewutype(L, &RETVAL, sizeof(R_AffineTransform), "R_AffineTransform");
    return 1;
}

static int r_sprite_origin_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 RETVAL;
    RETVAL = R_sprite_origin(self);
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_sprite_origin_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_origin_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_origin_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_origin_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_pos_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 RETVAL;
    RETVAL = R_sprite_pos(self);
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_sprite_pos_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_pos_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_pos_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_pos_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_scale_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 RETVAL;
    RETVAL = R_sprite_scale(self);
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_sprite_scale_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_scale_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_scale_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_scale_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_skew_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 RETVAL;
    RETVAL = R_sprite_skew(self);
    XL_pushnewutype(L, &RETVAL, sizeof(R_V2), "R_V2");
    return 1;
}

static int r_sprite_skew_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_skew_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_skew_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_skew_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_angle_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_angle(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_rotation_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_rotation(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_set_transform_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_AffineTransform VALUE = *((R_AffineTransform *)luaL_checkudata(L, 2, "R_AffineTransform"));
    R_sprite_transform_set(self, VALUE);
    return 0;
}

static int r_sprite_origin_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_origin_set(self, VALUE);
    return 0;
}

static int r_sprite_origin_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_origin_x_set(self, VALUE);
    return 0;
}

static int r_sprite_origin_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_origin_y_set(self, VALUE);
    return 0;
}

static int r_sprite_pos_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_pos_set(self, VALUE);
    return 0;
}

static int r_sprite_pos_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_x_set(self, VALUE);
    return 0;
}

static int r_sprite_pos_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_y_set(self, VALUE);
    return 0;
}

static int r_sprite_scale_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_scale_set(self, VALUE);
    return 0;
}

static int r_sprite_scale_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_scale_x_set(self, VALUE);
    return 0;
}

static int r_sprite_scale_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_scale_y_set(self, VALUE);
    return 0;
}

static int r_sprite_skew_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_skew_set(self, VALUE);
    return 0;
}

static int r_sprite_skew_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_skew_x_set(self, VALUE);
    return 0;
}

static int r_sprite_skew_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_skew_y_set(self, VALUE);
    return 0;
}

static int r_sprite_angle_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_angle_set(self, VALUE);
    return 0;
}

static int r_sprite_rotation_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_rotation_set(self, VALUE);
    return 0;
}

static int r_sprite_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_pos_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_x_set(self, VALUE);
    return 0;
}

static int r_sprite_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_pos_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_y_set(self, VALUE);
    return 0;
}

static int r_sprite_world_pos_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_world_pos_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_world_pos_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_world_pos_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_world_origin_x_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_world_origin_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_world_origin_y_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    float RETVAL;
    RETVAL = R_sprite_world_origin_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_method_orphan_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_sprite_orphan(self);
    return 0;
}

static int r_sprite_method_add_child_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_Sprite *child = XL_checkpptype(L, 2, "R_Sprite");
    int RETVAL;
    RETVAL = R_sprite_child_add(self, child);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_sprite_method_add_child_at_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_Sprite *child = XL_checkpptype(L, 2, "R_Sprite");
    int index = XL_checkint(L, 3);
    int RETVAL;
    RETVAL = R_sprite_child_add_at(self, child, index);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_sprite_method_remove_child_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_Sprite *child = XL_checkpptype(L, 2, "R_Sprite");
    R_sprite_child_remove(self, child);
    return 0;
}

static int r_sprite_method_child_index_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_Sprite *child = XL_checkpptype(L, 2, "R_Sprite");
    int RETVAL;
    RETVAL = R_sprite_child_index(self, child);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_sprite_method_draw_xl(lua_State *L)
{
    R_Sprite *self = XL_checkpptype(L, 1, "R_Sprite");
    R_Nvg *nvg = XL_checkpptype(L, 2, "R_Nvg");
    int logical_width = XL_checkint(L, 3);
    int logical_height = XL_checkint(L, 4);
    int target_width = XL_checkint(L, 5);
    int target_height = XL_checkint(L, 6);
    R_sprite_draw(self, nvg, logical_width, logical_height, target_width, target_height);
    return 0;
}

static int r_affinetransform_index_dummy_xl;
static int r_affinetransform_index_xl(lua_State *L)
{
    return XL_index(L, "R_AffineTransform", &r_affinetransform_index_dummy_xl, 1, 2);
}

static int r_sprite_index_dummy_xl;
static int r_sprite_index_xl(lua_State *L)
{
    return XL_index(L, "R_Sprite", &r_sprite_index_dummy_xl, 1, 2);
}

static int r_v2_index_dummy_xl;
static int r_v2_index_xl(lua_State *L)
{
    return XL_index(L, "R_V2", &r_v2_index_dummy_xl, 1, 2);
}

static int r_affinetransform_newindex_dummy_xl;
static int r_affinetransform_newindex_xl(lua_State *L)
{
    return XL_newindex(L, "R_AffineTransform", &r_affinetransform_newindex_dummy_xl, 1, 2, 3);
}

static int r_sprite_newindex_dummy_xl;
static int r_sprite_newindex_xl(lua_State *L)
{
    return XL_newindex(L, "R_Sprite", &r_sprite_newindex_dummy_xl, 1, 2, 3);
}

static int r_v2_newindex_dummy_xl;
static int r_v2_newindex_xl(lua_State *L)
{
    return XL_newindex(L, "R_V2", &r_v2_newindex_dummy_xl, 1, 2, 3);
}

static luaL_Reg r_sprite_function_registry_xl[] = {
    {"new", r_sprite_new_xl},
    {NULL, NULL},
};

static luaL_Reg r_v2_function_registry_xl[] = {
    {"new", r_v2_new_xl},
    {NULL, NULL},
};

static luaL_Reg r_affinetransform_index_registry_xl[] = {
    {"angle", r_affinetransform_angle_index_xl},
    {"origin", r_affinetransform_origin_index_xl},
    {"origin_x", r_affinetransform_origin_x_index_xl},
    {"origin_y", r_affinetransform_origin_y_index_xl},
    {"pos", r_affinetransform_pos_index_xl},
    {"pos_x", r_affinetransform_pos_x_index_xl},
    {"pos_y", r_affinetransform_pos_y_index_xl},
    {"scale", r_affinetransform_scale_index_xl},
    {"scale_x", r_affinetransform_scale_x_index_xl},
    {"scale_y", r_affinetransform_scale_y_index_xl},
    {"skew", r_affinetransform_skew_index_xl},
    {"skew_x", r_affinetransform_skew_x_index_xl},
    {"skew_y", r_affinetransform_skew_y_index_xl},
    {"x", r_affinetransform_x_index_xl},
    {"y", r_affinetransform_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_sprite_index_registry_xl[] = {
    {"angle", r_sprite_angle_index_xl},
    {"name", r_sprite_name_index_xl},
    {"origin", r_sprite_origin_index_xl},
    {"origin_x", r_sprite_origin_x_index_xl},
    {"origin_y", r_sprite_origin_y_index_xl},
    {"parent", r_sprite_parent_index_xl},
    {"pos", r_sprite_pos_index_xl},
    {"pos_x", r_sprite_pos_x_index_xl},
    {"pos_y", r_sprite_pos_y_index_xl},
    {"rotation", r_sprite_rotation_index_xl},
    {"scale", r_sprite_scale_index_xl},
    {"scale_x", r_sprite_scale_x_index_xl},
    {"scale_y", r_sprite_scale_y_index_xl},
    {"skew", r_sprite_skew_index_xl},
    {"skew_x", r_sprite_skew_x_index_xl},
    {"skew_y", r_sprite_skew_y_index_xl},
    {"transform", r_sprite_transform_index_xl},
    {"user", r_sprite_user_index_xl},
    {"world_origin_x", r_sprite_world_origin_x_index_xl},
    {"world_origin_y", r_sprite_world_origin_y_index_xl},
    {"world_pos_x", r_sprite_world_pos_x_index_xl},
    {"world_pos_y", r_sprite_world_pos_y_index_xl},
    {"x", r_sprite_x_index_xl},
    {"y", r_sprite_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_v2_index_registry_xl[] = {
    {"x", r_v2_x_index_xl},
    {"y", r_v2_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_affinetransform_method_registry_xl[] = {
    {"__index", r_affinetransform_index_xl},
    {"__newindex", r_affinetransform_newindex_xl},
    {"set", r_affinetransform_method_set_xl},
    {NULL, NULL},
};

static luaL_Reg r_sprite_method_registry_xl[] = {
    {"__gc", r_sprite_method_gc_xl},
    {"__index", r_sprite_index_xl},
    {"__newindex", r_sprite_newindex_xl},
    {"add_child", r_sprite_method_add_child_xl},
    {"add_child_at", r_sprite_method_add_child_at_xl},
    {"child_index", r_sprite_method_child_index_xl},
    {"draw", r_sprite_method_draw_xl},
    {"orphan", r_sprite_method_orphan_xl},
    {"remove_child", r_sprite_method_remove_child_xl},
    {"set", r_sprite_method_set_xl},
    {NULL, NULL},
};

static luaL_Reg r_v2_method_registry_xl[] = {
    {"__index", r_v2_index_xl},
    {"__newindex", r_v2_newindex_xl},
    {"__tostring", r_v2_method_tostring_xl},
    {"set", r_v2_method_set_xl},
    {"unpack", r_v2_method_unpack_xl},
    {NULL, NULL},
};

static luaL_Reg r_affinetransform_newindex_registry_xl[] = {
    {"angle", r_affinetransform_angle_newindex_xl},
    {"origin", r_affinetransform_origin_newindex_xl},
    {"origin_x", r_affinetransform_origin_x_newindex_xl},
    {"origin_y", r_affinetransform_origin_y_newindex_xl},
    {"pos", r_affinetransform_pos_newindex_xl},
    {"pos_x", r_affinetransform_pos_x_newindex_xl},
    {"pos_y", r_affinetransform_pos_y_newindex_xl},
    {"scale", r_affinetransform_scale_newindex_xl},
    {"scale_x", r_affinetransform_scale_x_newindex_xl},
    {"scale_y", r_affinetransform_scale_y_newindex_xl},
    {"skew", r_affinetransform_skew_newindex_xl},
    {"skew_x", r_affinetransform_skew_x_newindex_xl},
    {"skew_y", r_affinetransform_skew_y_newindex_xl},
    {"x", r_affinetransform_x_newindex_xl},
    {"y", r_affinetransform_y_newindex_xl},
    {NULL, NULL},
};

static luaL_Reg r_sprite_newindex_registry_xl[] = {
    {"angle", r_sprite_angle_newindex_xl},
    {"content", r_sprite_content_newindex_xl},
    {"name", r_sprite_name_newindex_xl},
    {"origin", r_sprite_origin_newindex_xl},
    {"origin_x", r_sprite_origin_x_newindex_xl},
    {"origin_y", r_sprite_origin_y_newindex_xl},
    {"pos", r_sprite_pos_newindex_xl},
    {"pos_x", r_sprite_pos_x_newindex_xl},
    {"pos_y", r_sprite_pos_y_newindex_xl},
    {"rotation", r_sprite_rotation_newindex_xl},
    {"scale", r_sprite_scale_newindex_xl},
    {"scale_x", r_sprite_scale_x_newindex_xl},
    {"scale_y", r_sprite_scale_y_newindex_xl},
    {"set_transform", r_sprite_set_transform_newindex_xl},
    {"skew", r_sprite_skew_newindex_xl},
    {"skew_x", r_sprite_skew_x_newindex_xl},
    {"skew_y", r_sprite_skew_y_newindex_xl},
    {"user", r_sprite_user_newindex_xl},
    {"x", r_sprite_x_newindex_xl},
    {"y", r_sprite_y_newindex_xl},
    {NULL, NULL},
};

static luaL_Reg r_v2_newindex_registry_xl[] = {
    {"x", r_v2_x_newindex_xl},
    {"y", r_v2_y_newindex_xl},
    {NULL, NULL},
};

int R_lua_sprite_init(lua_State *L)
{
    XL_initmetatable(L, "R_AffineTransform", r_affinetransform_method_registry_xl);
    XL_initmetatable(L, "R_Sprite", r_sprite_method_registry_xl);
    XL_initmetatable(L, "R_V2", r_v2_method_registry_xl);
    XL_initindextable(L, &r_affinetransform_index_dummy_xl, r_affinetransform_index_registry_xl);
    XL_initindextable(L, &r_sprite_index_dummy_xl, r_sprite_index_registry_xl);
    XL_initindextable(L, &r_v2_index_dummy_xl, r_v2_index_registry_xl);
    XL_initnewindextable(L, &r_affinetransform_newindex_dummy_xl, r_affinetransform_newindex_registry_xl);
    XL_initnewindextable(L, &r_sprite_newindex_dummy_xl, r_sprite_newindex_registry_xl);
    XL_initnewindextable(L, &r_v2_newindex_dummy_xl, r_v2_newindex_registry_xl);
    XL_initfunctions(L, r_sprite_function_registry_xl, "R", "Sprite", (const char *)NULL);
    XL_initfunctions(L, r_v2_function_registry_xl, "R", "V2", (const char *)NULL);
    return 0;
}
