/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_affinetransform_origin_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 RETVAL;
    RETVAL = self->origin;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_affinetransform_origin_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->origin = VALUE;
    return 0;
}

static int r_affinetransform_origin_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->origin.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_origin_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->origin.x = VALUE;
    return 0;
}

static int r_affinetransform_origin_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->origin.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_origin_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->origin.x = VALUE;
    return 0;
}

static int r_affinetransform_pos_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 RETVAL;
    RETVAL = self->pos;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_affinetransform_pos_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->pos = VALUE;
    return 0;
}

static int r_affinetransform_pos_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->pos.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_pos_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->pos.x = VALUE;
    return 0;
}

static int r_affinetransform_pos_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->pos.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_pos_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->pos.y = VALUE;
    return 0;
}

static int r_affinetransform_scale_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 RETVAL;
    RETVAL = self->scale;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_affinetransform_scale_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->scale = VALUE;
    return 0;
}

static int r_affinetransform_scale_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->scale.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_scale_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->scale.x = VALUE;
    return 0;
}

static int r_affinetransform_scale_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->scale.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_scale_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->scale.y = VALUE;
    return 0;
}

static int r_affinetransform_skew_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 RETVAL;
    RETVAL = self->skew;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_affinetransform_skew_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->skew = VALUE;
    return 0;
}

static int r_affinetransform_skew_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->skew.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_skew_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->skew.x = VALUE;
    return 0;
}

static int r_affinetransform_skew_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->skew.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_skew_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->skew.y = VALUE;
    return 0;
}

static int r_affinetransform_angle_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->angle;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_angle_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->angle = VALUE;
    return 0;
}

static int r_affinetransform_base_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 RETVAL;
    RETVAL = self->base;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_affinetransform_base_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    self->base = VALUE;
    return 0;
}

static int r_affinetransform_base_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->base.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_base_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->base.x = VALUE;
    return 0;
}

static int r_affinetransform_base_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->base.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_base_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->base.y = VALUE;
    return 0;
}

static int r_affinetransform_rotation_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = R_affine_transform_rotation(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_rotation_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    R_affine_transform_rotation_set(self, VALUE);
    return 0;
}

static int r_affinetransform_rel_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 RETVAL;
    RETVAL = R_affine_transform_rel(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_affinetransform_rel_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_affine_transform_rel_set(self, VALUE);
    return 0;
}

static int r_affinetransform_rel_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = R_affine_transform_rel_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_rel_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    R_affine_transform_rel_x_set(self, VALUE);
    return 0;
}

static int r_affinetransform_rel_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = R_affine_transform_rel_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_rel_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    R_affine_transform_rel_y_set(self, VALUE);
    return 0;
}

static int r_affinetransform_x_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->pos.x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_x_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->pos.x = VALUE;
    return 0;
}

static int r_affinetransform_y_index_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float RETVAL;
    RETVAL = self->pos.y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_affinetransform_y_newindex_xl(lua_State *L)
{
    R_AffineTransform *self = R_CPPCAST(R_AffineTransform *, XL_checkutype(L, 1, "R_AffineTransform"));
    float VALUE = XL_checkfloat(L, 2);
    self->pos.y = VALUE;
    return 0;
}

static int r_affinetransform_method_set_xl(lua_State *L)
{
    return XL_setfromtable(L, "R_AffineTransform", 1, 2);
}


typedef struct R_LuaSpriteData {
    R_MAGIC_FIELD
    lua_State *L;
    int       draw_reg;
    int       user_reg;
} R_LuaSpriteData;

static R_UserData lua_sprite_data_new(lua_State *L)
{
    R_LuaSpriteData *data = R_NEW_INIT_STRUCT(data, R_LuaSpriteData,
        R_MAGIC_INIT(R_LuaSpriteData) R_lua_main_state(L), LUA_NOREF, LUA_NOREF);
    R_MAGIC_CHECK(R_LuaSpriteData, data);
    return R_user_data(data);
}

static void lua_sprite_data_free(R_UserData user)
{
    R_LuaSpriteData *data = user.data;
    if (data) {
        R_MAGIC_CHECK(R_LuaSpriteData, data);
        lua_State *L = data->L;
        R_lua_unreg(L, data->draw_reg);
        R_lua_unreg(L, data->user_reg);
        free(data);
    }
}


static int r_sprite_new_xl(lua_State *L)
{
    luaL_checkany(L, 1);
    int name_index = 1;
    R_Sprite *RETVAL;
    int argc = lua_gettop(L);
    const char *name = lua_isnil(L, name_index) ? NULL
                     : luaL_checkstring(L, name_index);
    RETVAL   = R_sprite_new(name);
    R_sprite_user_set(RETVAL, lua_sprite_data_new(L), lua_sprite_data_free);
    XL_pushnewpptypeuv(L, RETVAL, "R_Sprite", 0);
    if (argc >= 2) {
        lua_getfield(L, -1, "set");
        lua_pushvalue(L, -2);
        lua_pushvalue(L, 2);
        lua_call(L, 2, 0);
    }
    return 1;
}

static int r_sprite_method_gc_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype_nullable(L, 1, "R_Sprite"));
    R_sprite_decref(self);
    return 0;
}

static int r_sprite_method_eq_xl(lua_State *L)
{
    luaL_checkany(L, 1);
    int a = 1;
    luaL_checkany(L, 2);
    int b = 2;
    bool RETVAL;
    R_Sprite **app = luaL_testudata(L, a, "R_Sprite");
    R_Sprite **bpp = luaL_testudata(L, b, "R_Sprite");
    RETVAL = app == bpp || (app && bpp && *app == *bpp);
    lua_pushboolean(L, RETVAL);
    return 1;
}

static int r_sprite_name_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    const char *RETVAL;
    RETVAL = R_sprite_name(self);
    lua_pushstring(L, RETVAL);
    return 1;
}

static int r_sprite_name_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    luaL_checkany(L, 2);
    int VALUE = 2;
    if (lua_isnil(L, VALUE)) {
        R_sprite_name_set(self, NULL);
    }
    else {
        const char *name = luaL_checkstring(L, VALUE);
        R_sprite_name_set(self, name);
    }
    return 0;
}

static int r_sprite_user_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    luaL_checkany(L, 2);
    int VALUE = 2;
    R_LuaSpriteData *data = R_sprite_user(self).data;
    R_MAGIC_CHECK(R_LuaSpriteData, data);
    R_lua_unreg(L, data->user_reg);
    data->user_reg = R_lua_reg_at(L, VALUE);
    return 0;
}

static int r_sprite_user_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_LuaSpriteData *data = R_sprite_user(self).data;
    R_MAGIC_CHECK(R_LuaSpriteData, data);
    R_lua_getreg(L, data->user_reg);
    return 1;
}

static int r_sprite_parent_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Sprite *RETVAL;
    RETVAL = R_sprite_parent(self);
    if (RETVAL) {
        R_sprite_incref(RETVAL);
    }
    XL_pushnewpptypeuv_nullable(L, RETVAL, "R_Sprite", 0);
    return 1;
}


static void draw_lua_value(R_Nvg *nvg, const float matrix[static 6],
                           R_UserData user)
{
    R_LUA_VALUE_DECLARE_UNPACK(user.data, lv, L);
    R_lua_getreg(L, lv->reg);
    XL_pushnewpptypeuv(L, nvg, "R_Nvg", 0);
    R_nvg_incref(nvg);
    XL_pushnewutypeuv(L, matrix, sizeof(R_LuaNvgTransform),
                      "R_LuaNvgTransform", 0);
    if (lua_pcall(L, 2, 0, 0)) {
        R_LUA_ERROR_TO_WARNING(L);
    }
}

static void free_lua_value(R_UserData user)
{
    R_lua_value_free(user.data);
}



static int r_sprite_content_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    luaL_checkany(L, 2);
    int VALUE = 2;
    void **pp;
    if ((pp = luaL_testudata(L, VALUE, "R_VectorImage"))) {
        R_VectorImage *field = *pp;
        R_sprite_draw_vector_image(self, field);
    }
    else if ((pp = luaL_testudata(L, VALUE, "R_BitmapImage"))) {
        R_BitmapImage *field = *pp;
        R_sprite_draw_bitmap_image(self, field);
    }
    else if ((pp = luaL_testudata(L, VALUE, "R_TextField"))) {
        R_TextField *field = *pp;
        R_sprite_draw_text_field(self, field);
    }
    else if (lua_isfunction(L, VALUE)) {
        R_LuaValue *lv = R_lua_value_new(L, VALUE);
        R_sprite_draw_fn(self, draw_lua_value, free_lua_value, R_user_data(lv));
    }
    else if (lua_isnil(L, VALUE)) {
        R_sprite_draw_null(self);
    }
    else {
        return luaL_error(L, "Don't know how to draw a value of type %s",
                          luaL_typename(L, VALUE));
    }
    /*
     * There's not really a sensible way to read the content back once set, but
     * that's a very useful thing to do to e.g. get the asset dimensions. So
     * we'll just remember the last value set and return it when requested. It
     * won't mix well with C code setting it though, since then we won't know.
     */
    R_LuaSpriteData *data = R_sprite_user(self).data;
    R_MAGIC_CHECK(R_LuaSpriteData, data);
    R_lua_unreg(L, data->draw_reg);
    data->draw_reg = R_lua_reg_at(L, VALUE);
    return 0;
}

static int r_sprite_content_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_LuaSpriteData *data = R_sprite_user(self).data;
    R_MAGIC_CHECK(R_LuaSpriteData, data);
    R_lua_getreg(L, data->draw_reg);
    return 1;
}

static int r_sprite_method_set_xl(lua_State *L)
{
    return XL_setfromtable(L, "R_Sprite", 1, 2);
}

static int r_sprite_matrix_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    int RETVAL;
    R_LuaNvgTransform tf;
    if (R_sprite_matrix(self, tf.matrix)) {
        XL_pushnewutypeuv(L, &tf, sizeof(tf), "R_LuaNvgTransform", 0);
    }
    else {
        lua_pushnil(L);
    }
    return 1;
    lua_pushvalue(L, RETVAL);
    return 1;
}

static int r_sprite_matrix_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    luaL_checkany(L, 2);
    int VALUE = 2;
    if (lua_isnil(L, VALUE)) {
        R_sprite_matrix_set(self, NULL);
    }
    else {
        R_LuaNvgTransform *tf = XL_checkutype(L, VALUE, "R_LuaNvgTransform");
        R_sprite_matrix_set(self, tf->matrix);
    }
    return 0;
}

static int r_sprite_transform_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_AffineTransform RETVAL;
    RETVAL = R_sprite_transform(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_AffineTransform), "R_AffineTransform", 0);
    return 1;
}

static int r_sprite_origin_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_origin(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_origin_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_origin_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_origin_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_origin_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_pos_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_pos(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_pos_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_pos_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_pos_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_pos_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_scale_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_scale(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_scale_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_scale_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_scale_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_scale_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_skew_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_skew(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_skew_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_skew_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_skew_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_skew_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_angle_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_angle(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_tint_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    NVGcolor RETVAL;
    RETVAL = R_sprite_tint(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(NVGcolor), "NVGcolor", 0);
    return 1;
}

static int r_sprite_color_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    NVGcolor RETVAL;
    RETVAL = R_sprite_tint(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(NVGcolor), "NVGcolor", 0);
    return 1;
}

static int r_sprite_alpha_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_alpha(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_base_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_base(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_base_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_base_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_base_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_base_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_rotation_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_rotation(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_rel_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_rel(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_rel_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_rel_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_rel_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_rel_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_set_transform_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_AffineTransform VALUE = *((R_AffineTransform *)luaL_checkudata(L, 2, "R_AffineTransform"));
    R_sprite_transform_set(self, VALUE);
    return 0;
}

static int r_sprite_origin_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_origin_set(self, VALUE);
    return 0;
}

static int r_sprite_origin_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_origin_x_set(self, VALUE);
    return 0;
}

static int r_sprite_origin_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_origin_y_set(self, VALUE);
    return 0;
}

static int r_sprite_pos_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_pos_set(self, VALUE);
    return 0;
}

static int r_sprite_pos_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_x_set(self, VALUE);
    return 0;
}

static int r_sprite_pos_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_y_set(self, VALUE);
    return 0;
}

static int r_sprite_scale_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_scale_set(self, VALUE);
    return 0;
}

static int r_sprite_scale_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_scale_x_set(self, VALUE);
    return 0;
}

static int r_sprite_scale_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_scale_y_set(self, VALUE);
    return 0;
}

static int r_sprite_skew_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_skew_set(self, VALUE);
    return 0;
}

static int r_sprite_skew_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_skew_x_set(self, VALUE);
    return 0;
}

static int r_sprite_skew_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_skew_y_set(self, VALUE);
    return 0;
}

static int r_sprite_angle_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_angle_set(self, VALUE);
    return 0;
}

static int r_sprite_alpha_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_alpha_set(self, VALUE);
    return 0;
}

static int r_sprite_tint_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    NVGcolor VALUE = *((NVGcolor *)luaL_checkudata(L, 2, "NVGcolor"));
    R_sprite_tint_set(self, VALUE);
    return 0;
}

static int r_sprite_color_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    NVGcolor VALUE = *((NVGcolor *)luaL_checkudata(L, 2, "NVGcolor"));
    R_sprite_tint_set(self, VALUE);
    return 0;
}

static int r_sprite_base_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_base_set(self, VALUE);
    return 0;
}

static int r_sprite_base_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_base_x_set(self, VALUE);
    return 0;
}

static int r_sprite_base_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_base_y_set(self, VALUE);
    return 0;
}

static int r_sprite_rotation_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_rotation_set(self, VALUE);
    return 0;
}

static int r_sprite_rel_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 VALUE = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_sprite_rel_set(self, VALUE);
    return 0;
}

static int r_sprite_rel_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_rel_x_set(self, VALUE);
    return 0;
}

static int r_sprite_rel_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_rel_y_set(self, VALUE);
    return 0;
}

static int r_sprite_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_pos_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_x_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_x_set(self, VALUE);
    return 0;
}

static int r_sprite_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_pos_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_y_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_pos_y_set(self, VALUE);
    return 0;
}

static int r_sprite_scales_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    R_V2 scale = R_sprite_scale(self);
    RETVAL = (scale.x * 0.5f) + (scale.y * 0.5f);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_scales_newindex_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float VALUE = XL_checkfloat(L, 2);
    R_sprite_scale_set(self, R_v2(VALUE, VALUE));
    return 0;
}

static int r_sprite_world_pos_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_world_pos(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_world_pos_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_world_pos_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_world_pos_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_world_pos_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_world_origin_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 RETVAL;
    RETVAL = R_sprite_world_origin(self);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_world_origin_x_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_world_origin_x(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_world_origin_y_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    float RETVAL;
    RETVAL = R_sprite_world_origin_y(self);
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_sprite_method_to_local_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 point = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_V2 RETVAL;
    RETVAL = R_sprite_to_local(self, point);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_method_to_world_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_V2 point = *((R_V2 *)luaL_checkudata(L, 2, "R_V2"));
    R_V2 RETVAL;
    RETVAL = R_sprite_to_world(self, point);
    XL_pushnewutypeuv(L, &RETVAL, sizeof(R_V2), "R_V2", 0);
    return 1;
}

static int r_sprite_method_reset_base_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_sprite_base_set(self, R_sprite_pos(self));
    return 0;
}

static int r_sprite_method_track_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    luaL_checkany(L, 2);
    int arg = 2;
    R_Sprite *tracking;
    if (lua_isnil(L, arg)) {
        tracking = NULL;
    }
    else {
        tracking = XL_checkpptype(L, arg, "R_Sprite");
    }
    R_sprite_track(self, tracking);
    return 0;
}

static int r_sprite_method_orphan_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_sprite_orphan(self);
    return 0;
}

static int r_sprite_method_add_child_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Sprite *child = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 2, "R_Sprite"));
    int RETVAL;
    RETVAL = R_sprite_child_add(self, child);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_sprite_method_add_child_at_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Sprite *child = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 2, "R_Sprite"));
    int index = XL_checkint(L, 3);
    int RETVAL;
    RETVAL = R_sprite_child_add_at(self, child, index);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_sprite_method_remove_child_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Sprite *child = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 2, "R_Sprite"));
    R_sprite_child_remove(self, child);
    return 0;
}

static int r_sprite_method_child_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Sprite *child = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 2, "R_Sprite"));
    int RETVAL;
    RETVAL = R_sprite_child_index(self, child);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_sprite_index_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Sprite *parent = R_sprite_parent(self);
    if (parent) {
        XL_pushint(L, R_sprite_child_index(parent, self));
    }
    else {
        lua_pushnil(L);
    }
    return 1;
}


static int push_sprite_or_nil(lua_State *L, R_Sprite *sprite)
{
    if (sprite) {
        XL_pushnewpptypeuv(L, R_sprite_incref(sprite), "R_Sprite", 0);
    }
    else {
        lua_pushnil(L);
    }
    return 1;
}

static int child_iterator(lua_State *L)
{
    if (lua_toboolean(L, 2)) {
        lua_getfield(L, 2, "next");
    }
    else {
        lua_getfield(L, 1, "first_child");
    }
    return 1;
}


static int r_sprite_first_child_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    return push_sprite_or_nil(L, R_sprite_child_first(self));
}

static int r_sprite_next_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    return push_sprite_or_nil(L, R_sprite_next(self));
}

static int r_sprite_children_index_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    lua_newtable(L);
    R_Sprite    *child = R_sprite_child_first(self);
    lua_Integer index  = 1;
    while (child) {
        XL_pushnewpptypeuv(L, R_sprite_incref(child), "R_Sprite", 0);
        lua_seti(L, -2, index);
        child = R_sprite_next(child);
        ++index;
    }
    return 1;
}

static int r_sprite_method_iterate_children_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    XL_UNUSED(self);
    lua_pushcfunction(L, child_iterator);
    lua_pushvalue(L, 1);
    return 2;
}

static int r_sprite_method_draw_xl(lua_State *L)
{
    R_Sprite *self = R_CPPCAST(R_Sprite *, XL_checkpptype(L, 1, "R_Sprite"));
    R_Nvg *nvg = R_CPPCAST(R_Nvg *, XL_checkpptype(L, 2, "R_Nvg"));
    int logical_width = XL_checkint(L, 3);
    int logical_height = XL_checkint(L, 4);
    int target_width = XL_checkint(L, 5);
    int target_height = XL_checkint(L, 6);
    R_sprite_draw(self, nvg, logical_width, logical_height, target_width, target_height);
    return 0;
}

#ifdef __cplusplus
extern "C" {
#endif

static int r_affinetransform_index_anchor_xl;
static int r_affinetransform_index_xl(lua_State *L)
{
    return XL_index(L, "R_AffineTransform", &r_affinetransform_index_anchor_xl, 1, 2);
}

static int r_sprite_index_anchor_xl;
static int r_sprite_index_xl(lua_State *L)
{
    return XL_index(L, "R_Sprite", &r_sprite_index_anchor_xl, 1, 2);
}

int r_affinetransform_newindex_anchor_xl;
static int r_affinetransform_newindex_xl(lua_State *L)
{
    return XL_newindex(L, "R_AffineTransform", &r_affinetransform_newindex_anchor_xl, 1, 2, 3);
}

int r_sprite_newindex_anchor_xl;
static int r_sprite_newindex_xl(lua_State *L)
{
    return XL_newindex(L, "R_Sprite", &r_sprite_newindex_anchor_xl, 1, 2, 3);
}

static luaL_Reg r_sprite_function_registry_xl[] = {
    {"new", r_sprite_new_xl},
    {NULL, NULL},
};

static luaL_Reg r_affinetransform_index_registry_xl[] = {
    {"angle", r_affinetransform_angle_index_xl},
    {"base", r_affinetransform_base_index_xl},
    {"base_x", r_affinetransform_base_x_index_xl},
    {"base_y", r_affinetransform_base_y_index_xl},
    {"origin", r_affinetransform_origin_index_xl},
    {"origin_x", r_affinetransform_origin_x_index_xl},
    {"origin_y", r_affinetransform_origin_y_index_xl},
    {"pos", r_affinetransform_pos_index_xl},
    {"pos_x", r_affinetransform_pos_x_index_xl},
    {"pos_y", r_affinetransform_pos_y_index_xl},
    {"rel", r_affinetransform_rel_index_xl},
    {"rel_x", r_affinetransform_rel_x_index_xl},
    {"rel_y", r_affinetransform_rel_y_index_xl},
    {"rotation", r_affinetransform_rotation_index_xl},
    {"scale", r_affinetransform_scale_index_xl},
    {"scale_x", r_affinetransform_scale_x_index_xl},
    {"scale_y", r_affinetransform_scale_y_index_xl},
    {"skew", r_affinetransform_skew_index_xl},
    {"skew_x", r_affinetransform_skew_x_index_xl},
    {"skew_y", r_affinetransform_skew_y_index_xl},
    {"x", r_affinetransform_x_index_xl},
    {"y", r_affinetransform_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_sprite_index_registry_xl[] = {
    {"alpha", r_sprite_alpha_index_xl},
    {"angle", r_sprite_angle_index_xl},
    {"base", r_sprite_base_index_xl},
    {"base_x", r_sprite_base_x_index_xl},
    {"base_y", r_sprite_base_y_index_xl},
    {"children", r_sprite_children_index_xl},
    {"color", r_sprite_color_index_xl},
    {"content", r_sprite_content_index_xl},
    {"first_child", r_sprite_first_child_index_xl},
    {"index", r_sprite_index_index_xl},
    {"matrix", r_sprite_matrix_index_xl},
    {"name", r_sprite_name_index_xl},
    {"next", r_sprite_next_index_xl},
    {"origin", r_sprite_origin_index_xl},
    {"origin_x", r_sprite_origin_x_index_xl},
    {"origin_y", r_sprite_origin_y_index_xl},
    {"parent", r_sprite_parent_index_xl},
    {"pos", r_sprite_pos_index_xl},
    {"pos_x", r_sprite_pos_x_index_xl},
    {"pos_y", r_sprite_pos_y_index_xl},
    {"rel", r_sprite_rel_index_xl},
    {"rel_x", r_sprite_rel_x_index_xl},
    {"rel_y", r_sprite_rel_y_index_xl},
    {"rotation", r_sprite_rotation_index_xl},
    {"scale", r_sprite_scale_index_xl},
    {"scale_x", r_sprite_scale_x_index_xl},
    {"scale_y", r_sprite_scale_y_index_xl},
    {"scales", r_sprite_scales_index_xl},
    {"skew", r_sprite_skew_index_xl},
    {"skew_x", r_sprite_skew_x_index_xl},
    {"skew_y", r_sprite_skew_y_index_xl},
    {"tint", r_sprite_tint_index_xl},
    {"transform", r_sprite_transform_index_xl},
    {"user", r_sprite_user_index_xl},
    {"world_origin", r_sprite_world_origin_index_xl},
    {"world_origin_x", r_sprite_world_origin_x_index_xl},
    {"world_origin_y", r_sprite_world_origin_y_index_xl},
    {"world_pos", r_sprite_world_pos_index_xl},
    {"world_pos_x", r_sprite_world_pos_x_index_xl},
    {"world_pos_y", r_sprite_world_pos_y_index_xl},
    {"x", r_sprite_x_index_xl},
    {"y", r_sprite_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_affinetransform_method_registry_xl[] = {
    {"__index", r_affinetransform_index_xl},
    {"__newindex", r_affinetransform_newindex_xl},
    {"set", r_affinetransform_method_set_xl},
    {NULL, NULL},
};

static luaL_Reg r_sprite_method_registry_xl[] = {
    {"__eq", r_sprite_method_eq_xl},
    {"__gc", r_sprite_method_gc_xl},
    {"__index", r_sprite_index_xl},
    {"__newindex", r_sprite_newindex_xl},
    {"add_child", r_sprite_method_add_child_xl},
    {"add_child_at", r_sprite_method_add_child_at_xl},
    {"child_index", r_sprite_method_child_index_xl},
    {"draw", r_sprite_method_draw_xl},
    {"iterate_children", r_sprite_method_iterate_children_xl},
    {"orphan", r_sprite_method_orphan_xl},
    {"remove_child", r_sprite_method_remove_child_xl},
    {"reset_base", r_sprite_method_reset_base_xl},
    {"set", r_sprite_method_set_xl},
    {"to_local", r_sprite_method_to_local_xl},
    {"to_world", r_sprite_method_to_world_xl},
    {"track", r_sprite_method_track_xl},
    {NULL, NULL},
};

static luaL_Reg r_affinetransform_newindex_registry_xl[] = {
    {"angle", r_affinetransform_angle_newindex_xl},
    {"base", r_affinetransform_base_newindex_xl},
    {"base_x", r_affinetransform_base_x_newindex_xl},
    {"base_y", r_affinetransform_base_y_newindex_xl},
    {"origin", r_affinetransform_origin_newindex_xl},
    {"origin_x", r_affinetransform_origin_x_newindex_xl},
    {"origin_y", r_affinetransform_origin_y_newindex_xl},
    {"pos", r_affinetransform_pos_newindex_xl},
    {"pos_x", r_affinetransform_pos_x_newindex_xl},
    {"pos_y", r_affinetransform_pos_y_newindex_xl},
    {"rel", r_affinetransform_rel_newindex_xl},
    {"rel_x", r_affinetransform_rel_x_newindex_xl},
    {"rel_y", r_affinetransform_rel_y_newindex_xl},
    {"rotation", r_affinetransform_rotation_newindex_xl},
    {"scale", r_affinetransform_scale_newindex_xl},
    {"scale_x", r_affinetransform_scale_x_newindex_xl},
    {"scale_y", r_affinetransform_scale_y_newindex_xl},
    {"skew", r_affinetransform_skew_newindex_xl},
    {"skew_x", r_affinetransform_skew_x_newindex_xl},
    {"skew_y", r_affinetransform_skew_y_newindex_xl},
    {"x", r_affinetransform_x_newindex_xl},
    {"y", r_affinetransform_y_newindex_xl},
    {NULL, NULL},
};

static luaL_Reg r_sprite_newindex_registry_xl[] = {
    {"alpha", r_sprite_alpha_newindex_xl},
    {"angle", r_sprite_angle_newindex_xl},
    {"base", r_sprite_base_newindex_xl},
    {"base_x", r_sprite_base_x_newindex_xl},
    {"base_y", r_sprite_base_y_newindex_xl},
    {"color", r_sprite_color_newindex_xl},
    {"content", r_sprite_content_newindex_xl},
    {"matrix", r_sprite_matrix_newindex_xl},
    {"name", r_sprite_name_newindex_xl},
    {"origin", r_sprite_origin_newindex_xl},
    {"origin_x", r_sprite_origin_x_newindex_xl},
    {"origin_y", r_sprite_origin_y_newindex_xl},
    {"pos", r_sprite_pos_newindex_xl},
    {"pos_x", r_sprite_pos_x_newindex_xl},
    {"pos_y", r_sprite_pos_y_newindex_xl},
    {"rel", r_sprite_rel_newindex_xl},
    {"rel_x", r_sprite_rel_x_newindex_xl},
    {"rel_y", r_sprite_rel_y_newindex_xl},
    {"rotation", r_sprite_rotation_newindex_xl},
    {"scale", r_sprite_scale_newindex_xl},
    {"scale_x", r_sprite_scale_x_newindex_xl},
    {"scale_y", r_sprite_scale_y_newindex_xl},
    {"scales", r_sprite_scales_newindex_xl},
    {"set_transform", r_sprite_set_transform_newindex_xl},
    {"skew", r_sprite_skew_newindex_xl},
    {"skew_x", r_sprite_skew_x_newindex_xl},
    {"skew_y", r_sprite_skew_y_newindex_xl},
    {"tint", r_sprite_tint_newindex_xl},
    {"user", r_sprite_user_newindex_xl},
    {"x", r_sprite_x_newindex_xl},
    {"y", r_sprite_y_newindex_xl},
    {NULL, NULL},
};

int R_lua_sprite_init(lua_State *L)
{
    XL_initmetatable(L, "R_AffineTransform", r_affinetransform_method_registry_xl);
    XL_initmetatable(L, "R_Sprite", r_sprite_method_registry_xl);
    XL_initindextable(L, &r_affinetransform_index_anchor_xl, r_affinetransform_index_registry_xl);
    XL_initindextable(L, &r_sprite_index_anchor_xl, r_sprite_index_registry_xl);
    XL_initnewindextable(L, &r_affinetransform_newindex_anchor_xl, r_affinetransform_newindex_registry_xl);
    XL_initnewindextable(L, &r_sprite_newindex_anchor_xl, r_sprite_newindex_registry_xl);
    XL_initfunctions(L, r_sprite_function_registry_xl, "R", "Sprite", (const char *)NULL);
    return 0;
}

#ifdef __cplusplus
}
#endif
