/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_textfield_new_xl(lua_State *L)
{
    R_TextField *RETVAL;
    int argc = lua_gettop(L);
    RETVAL   = R_text_field_new();
    XL_pushnewpptypeuv(L, RETVAL, "R_TextField", 0);
    if (argc >= 1) {
        lua_getfield(L, -1, "set");
        lua_pushvalue(L, -2);
        lua_pushvalue(L, 1);
        lua_call(L, 2, 0);
    }
    return 1;
}

static int r_textfield_method_gc_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype_nullable(L, 1, "R_TextField");
    R_text_field_decref(self);
    return 0;
}

static int r_textfield_string_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    R_String *RETVAL;
    R_MAGIC_CHECK(R_TextField, self);
    RETVAL = self->string;
    R_lua_push_r_string(L, RETVAL);
    return 1;
}

static int r_textfield_string_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    size_t VALUE_len;
    const char *VALUE = luaL_checklstring(L, 2, &VALUE_len);
    R_MAGIC_CHECK(R_TextField, self);
    R_String *string = self->string;
    if (string) {
        R_string_clear(string);
        R_string_append_bin(string, VALUE, VALUE_len);
    }
    else {
        self->string = R_string_from_bin(VALUE, VALUE_len);
    }
    return 0;
}

static int r_textfield_refs_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    int RETVAL;
    RETVAL = self->refs;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_textfield_font_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    int RETVAL;
    RETVAL = self->font;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_textfield_font_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    int VALUE = XL_checkint(L, 2);
    self->font = VALUE;
    return 0;
}

static int r_textfield_color_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    NVGcolor RETVAL;
    RETVAL = self->color;
    XL_pushnewutypeuv(L, &RETVAL, sizeof(NVGcolor), "NVGcolor", 0);
    return 1;
}

static int r_textfield_color_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    NVGcolor VALUE = *((NVGcolor *)luaL_checkudata(L, 2, "NVGcolor"));
    self->color = VALUE;
    return 0;
}

static int r_textfield_size_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->size;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_size_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->size = VALUE;
    return 0;
}

static int r_textfield_blur_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->blur;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_blur_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->blur = VALUE;
    return 0;
}

static int r_textfield_spacing_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->spacing;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_spacing_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->spacing = VALUE;
    return 0;
}

static int r_textfield_line_height_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->line_height;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_line_height_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->line_height = VALUE;
    return 0;
}

static int r_textfield_align_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    int RETVAL;
    RETVAL = self->align;
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_textfield_align_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    int VALUE = XL_checkint(L, 2);
    self->align = VALUE;
    return 0;
}

static int r_textfield_x_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->x;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_x_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->x = VALUE;
    return 0;
}

static int r_textfield_y_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->y;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_y_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->y = VALUE;
    return 0;
}

static int r_textfield_width_index_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float RETVAL;
    RETVAL = self->width;
    XL_pushfloat(L, RETVAL);
    return 1;
}

static int r_textfield_width_newindex_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    float VALUE = XL_checkfloat(L, 2);
    self->width = VALUE;
    return 0;
}

static int r_textfield_method_set_xl(lua_State *L)
{
    return XL_setfromtable(L, "R_TextField", 1, 2);
}

static int r_textfield_method_bounds_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    R_Nvg *nvg = XL_checkpptype(L, 2, "R_Nvg");
    R_V4 bounds = R_text_field_bounds(self, R_nvg_context(nvg));
    XL_pushfloat(L, bounds.x);
    XL_pushfloat(L, bounds.y);
    XL_pushfloat(L, bounds.z);
    XL_pushfloat(L, bounds.w);
    return 4;
}

static int r_textfield_method_draw_xl(lua_State *L)
{
    R_TextField *self = XL_checkpptype(L, 1, "R_TextField");
    R_Nvg *nvg = XL_checkpptype(L, 2, "R_Nvg");
    R_LuaNvgTransform *transform = XL_checkutype(L, 3, "R_LuaNvgTransform");
    R_text_field_draw(self, R_nvg_context(nvg), transform->matrix);
    return 0;
}

static int r_textfield_index_dummy_xl;
static int r_textfield_index_xl(lua_State *L)
{
    return XL_index(L, "R_TextField", &r_textfield_index_dummy_xl, 1, 2);
}

static int r_textfield_newindex_dummy_xl;
static int r_textfield_newindex_xl(lua_State *L)
{
    return XL_newindex(L, "R_TextField", &r_textfield_newindex_dummy_xl, 1, 2, 3);
}

static luaL_Reg r_textfield_function_registry_xl[] = {
    {"new", r_textfield_new_xl},
    {NULL, NULL},
};

static luaL_Reg r_textfield_index_registry_xl[] = {
    {"align", r_textfield_align_index_xl},
    {"blur", r_textfield_blur_index_xl},
    {"color", r_textfield_color_index_xl},
    {"font", r_textfield_font_index_xl},
    {"line_height", r_textfield_line_height_index_xl},
    {"refs", r_textfield_refs_index_xl},
    {"size", r_textfield_size_index_xl},
    {"spacing", r_textfield_spacing_index_xl},
    {"string", r_textfield_string_index_xl},
    {"width", r_textfield_width_index_xl},
    {"x", r_textfield_x_index_xl},
    {"y", r_textfield_y_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_textfield_method_registry_xl[] = {
    {"__gc", r_textfield_method_gc_xl},
    {"__index", r_textfield_index_xl},
    {"__newindex", r_textfield_newindex_xl},
    {"bounds", r_textfield_method_bounds_xl},
    {"draw", r_textfield_method_draw_xl},
    {"set", r_textfield_method_set_xl},
    {NULL, NULL},
};

static luaL_Reg r_textfield_newindex_registry_xl[] = {
    {"align", r_textfield_align_newindex_xl},
    {"blur", r_textfield_blur_newindex_xl},
    {"color", r_textfield_color_newindex_xl},
    {"font", r_textfield_font_newindex_xl},
    {"line_height", r_textfield_line_height_newindex_xl},
    {"size", r_textfield_size_newindex_xl},
    {"spacing", r_textfield_spacing_newindex_xl},
    {"string", r_textfield_string_newindex_xl},
    {"width", r_textfield_width_newindex_xl},
    {"x", r_textfield_x_newindex_xl},
    {"y", r_textfield_y_newindex_xl},
    {NULL, NULL},
};

int R_lua_text_field_init(lua_State *L)
{
    XL_initmetatable(L, "R_TextField", r_textfield_method_registry_xl);
    XL_initindextable(L, &r_textfield_index_dummy_xl, r_textfield_index_registry_xl);
    XL_initnewindextable(L, &r_textfield_newindex_dummy_xl, r_textfield_newindex_registry_xl);
    XL_initfunctions(L, r_textfield_function_registry_xl, "R", "TextField", (const char *)NULL);
    return 0;
}
