/*************************************************/
/* This file was auto-generated by xlgen.        */
/* Don't edit it directly, it'll be overwritten! */
/* Modify the matching .xl file and rebuild.     */
/*************************************************/
/*
 * Copyright (c) 2019 askmeaboutloom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#include <rouse.h>
#include "lua_inc.h"
#include "intern.h"
#include "util.h"


static int r_vectorimage_from_file_xl(lua_State *L)
{
    const char *path = luaL_checkstring(L, 1);
    R_VectorImage *RETVAL;
    RETVAL = R_vector_image_from_file(path);
    XL_pushnewpptype(L, RETVAL, "R_VectorImage");
    return 1;
}

static int r_vectorimage_method_gc_xl(lua_State *L)
{
    R_VectorImage *self = XL_checkpptype_nullable(L, 1, "R_VectorImage");
    R_vector_image_decref(self);
    return 0;
}

static int r_vectorimage_refs_index_xl(lua_State *L)
{
    R_VectorImage *self = XL_checkpptype(L, 1, "R_VectorImage");
    int RETVAL;
    RETVAL = R_vector_image_refs(self);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_vectorimage_width_index_xl(lua_State *L)
{
    R_VectorImage *self = XL_checkpptype(L, 1, "R_VectorImage");
    int RETVAL;
    RETVAL = R_vector_image_width(self);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_vectorimage_height_index_xl(lua_State *L)
{
    R_VectorImage *self = XL_checkpptype(L, 1, "R_VectorImage");
    int RETVAL;
    RETVAL = R_vector_image_height(self);
    XL_pushint(L, RETVAL);
    return 1;
}

static int r_vectorimage_method_draw_xl(lua_State *L)
{
    R_VectorImage *self = XL_checkpptype(L, 1, "R_VectorImage");
    R_Nvg *nvg = XL_checkpptype(L, 2, "R_Nvg");
    R_LuaNvgTransform *m = XL_checkutype(L, 3, "R_LuaNvgTransform");
    R_vector_image_draw(self, R_nvg_context(nvg), m->matrix);
    return 0;
}

static int r_vectorimage_index_dummy_xl;
static int r_vectorimage_index_xl(lua_State *L)
{
    return XL_index(L, "R_VectorImage", &r_vectorimage_index_dummy_xl, 1, 2);
}

static luaL_Reg r_vectorimage_function_registry_xl[] = {
    {"from_file", r_vectorimage_from_file_xl},
    {NULL, NULL},
};

static luaL_Reg r_vectorimage_index_registry_xl[] = {
    {"height", r_vectorimage_height_index_xl},
    {"refs", r_vectorimage_refs_index_xl},
    {"width", r_vectorimage_width_index_xl},
    {NULL, NULL},
};

static luaL_Reg r_vectorimage_method_registry_xl[] = {
    {"__gc", r_vectorimage_method_gc_xl},
    {"__index", r_vectorimage_index_xl},
    {"draw", r_vectorimage_method_draw_xl},
    {NULL, NULL},
};

int R_lua_vector_image_init(lua_State *L)
{
    XL_initmetatable(L, "R_VectorImage", r_vectorimage_method_registry_xl);
    XL_initindextable(L, &r_vectorimage_index_dummy_xl, r_vectorimage_index_registry_xl);
    XL_initfunctions(L, r_vectorimage_function_registry_xl, "R", "VectorImage", (const char *)NULL);
    return 0;
}
