if(USE_CLANG_TIDY AND NOT DEFINED CMAKE_C_CLANG_TIDY)
    find_program(clang_tidy NAMES "clang-tidy")
    if(clang_tidy)
        message(STATUS "Found clang-tidy, using it for all targets")
        set(CMAKE_C_CLANG_TIDY "${clang_tidy}")
    else()
        message(STATUS "Didn't find clang-tidy, so no linting for you")
    endif()
else()
    message(STATUS "Not using clang-tidy as requested")
endif()
