include("${CMAKE_CURRENT_LIST_DIR}/build_options.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/warnings.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/asan.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/clang_tidy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/c_standard.cmake")
